# -*- coding: utf-8 -*-
"""Dzial I — organizacja bezpiecznej pracy, partia druga. Ciezar egzaminu DOZOROWEGO."""

P = [
 dict(id="I-19", dzial="I", zakres=["D"], podstawa="BHP2019",
  pytanie="Kto może pełnić funkcję kierującego zespołem?",
  odp=["Osoba wyznaczona w poleceniu, posiadająca odpowiednie kwalifikacje i znajomość zagrożeń",
       "Dowolny członek zespołu wybrany przez pozostałych",
       "Wyłącznie osoba z uprawnieniami dozoru",
       "Przedstawiciel służby BHP"],
  ok=0,
  wyj="Kierującego wyznacza poleceniodawca w treści polecenia. Kierujący odpowiada za bezpieczeństwo zespołu w trakcie pracy i może ją przerwać."),

 dict(id="I-20", dzial="I", zakres=["D"], podstawa="BHP2019",
  pytanie="Czy jedna osoba może łączyć funkcje dopuszczającego i kierującego zespołem?",
  odp=["Tak, jeżeli pozwala na to organizacja pracy u prowadzącego eksploatację i osoba ma odpowiednie kwalifikacje",
       "Nie, jest to zawsze zabronione",
       "Tak, ale tylko przy pracach do 1 kV",
       "Tak, zawsze i bez żadnych warunków"],
  ok=0,
  wyj="Łączenie funkcji jest dopuszczalne w określonych przypadkach, ale nie wolno łączyć ich dowolnie. Zasady musi określać organizacja pracy u prowadzącego eksploatację."),

 dict(id="I-21", dzial="I", zakres=["D"], podstawa="BHP2019",
  pytanie="Ile egzemplarzy polecenia pisemnego się sporządza i kto je otrzymuje?",
  odp=["Co najmniej dwa — jeden zostaje u poleceniodawcy, drugi otrzymuje kierujący zespołem lub dopuszczający",
       "Jeden, który zostaje w aktach",
       "Cztery, po jednym dla każdej osoby funkcyjnej",
       "Liczba jest dowolna"],
  ok=0,
  wyj="Egzemplarze rozdziela się tak, aby osoby odpowiedzialne miały dokument przy sobie. Polecenia przechowuje się przez okres określony przez prowadzącego eksploatację."),

 dict(id="I-22", dzial="I", zakres=["D"], podstawa="BHP2019",
  pytanie="Co należy zrobić, gdy praca na polecenie przeciąga się na następną zmianę?",
  odp=["Przekazać pracę zgodnie z ustaloną procedurą, z odnotowaniem stanu zabezpieczeń",
       "Zakończyć pracę i rozpocząć nową na nowym poleceniu bez żadnych formalności",
       "Kontynuować bez żadnych czynności",
       "Zdjąć wszystkie zabezpieczenia na czas zmiany"],
  ok=0,
  wyj="Zdjęcie zabezpieczeń między zmianami byłoby groźnym błędem. Przekazanie musi obejmować stan strefy pracy i zabezpieczeń."),

 dict(id="I-23", dzial="I", zakres=["D","E"], podstawa="BHP2019",
  pytanie="Które prace zalicza się do szczególnie niebezpiecznych przy urządzeniach energetycznych?",
  odp=["Prace pod napięciem, w pobliżu napięcia oraz w warunkach szczególnego zagrożenia",
       "Wszystkie prace konserwacyjne",
       "Wyłącznie prace na wysokości",
       "Prace trwające dłużej niż osiem godzin"],
  ok=0,
  wyj="Takie prace wymagają polecenia pisemnego, co najmniej dwóch osób i szczególnych środków zabezpieczających."),

 dict(id="I-24", dzial="I", zakres=["D"], podstawa="BHP2019",
  pytanie="Czym różni się praca w pobliżu napięcia od pracy pod napięciem?",
  odp=["Przy pracy w pobliżu nie dotyka się części czynnych, ale można znaleźć się w strefie niebezpiecznej",
       "To dwa określenia tej samej sytuacji",
       "Praca w pobliżu napięcia nie wymaga żadnych zabezpieczeń",
       "Praca pod napięciem dotyczy wyłącznie urządzeń powyżej 1 kV"],
  ok=0,
  wyj="Obie są niebezpieczne, ale wymagają innych środków. Przy pracy w pobliżu stosuje się osłony i wygrodzenia, przy pracy pod napięciem specjalną technologię i sprzęt."),

 dict(id="I-25", dzial="I", zakres=["D","E"], podstawa="BHP2019",
  pytanie="Jakie oznaczenia stosuje się przy wyłączonych łącznikach w strefie pracy?",
  odp=["Tablice ostrzegawcze zakazujące załączania, np. „Nie załączać — pracują ludzie”",
       "Wyłącznie taśmę ostrzegawczą",
       "Żadne, wystarczy wyłączenie",
       "Oznaczenia kolorystyczne przewodów"],
  ok=0,
  wyj="Oprócz tablic stosuje się blokady mechaniczne łączników. Samo wyłączenie nie chroni przed przypadkowym załączeniem przez inną osobę."),

 dict(id="I-26", dzial="I", zakres=["D"], podstawa="BHP2019",
  pytanie="Kto może zdjąć zabezpieczenia i uziemienia po zakończeniu pracy?",
  odp=["Dopuszczający albo osoba przez niego upoważniona, po wyprowadzeniu zespołu ze strefy",
       "Każdy członek zespołu",
       "Kierujący zespołem w dowolnym momencie",
       "Poleceniodawca telefonicznie"],
  ok=0,
  wyj="Kolejność jest krytyczna: najpierw zespół opuszcza strefę, dopiero potem znikają zabezpieczenia. Odwrotna kolejność to bezpośrednie zagrożenie życia."),

 dict(id="I-27", dzial="I", zakres=["D"], podstawa="KP",
  pytanie="Czy osoba dozoru może dopuścić do pracy pracownika bez aktualnych badań lekarskich?",
  odp=["Nie, brak aktualnych badań wyklucza dopuszczenie do pracy",
       "Tak, jeżeli pracownik czuje się dobrze",
       "Tak, przy pracach do 1 kV",
       "Tak, na własną odpowiedzialność pracownika"],
  ok=0,
  wyj="To obowiązek bezwzględny wynikający z Kodeksu pracy. Dopuszczenie bez badań obciąża osobę kierującą pracownikami."),

 dict(id="I-28", dzial="I", zakres=["D"], podstawa="KP",
  pytanie="Jakie szkolenia BHP są wymagane przed dopuszczeniem pracownika do pracy?",
  odp=["Szkolenie wstępne: instruktaż ogólny i stanowiskowy",
       "Wyłącznie szkolenie okresowe",
       "Żadne, jeżeli pracownik ma doświadczenie",
       "Wyłącznie instruktaż ogólny"],
  ok=0,
  wyj="Szkolenie okresowe przychodzi później i powtarza się w ustalonych odstępach. Bez instruktażu stanowiskowego nie wolno dopuścić do pracy."),

 dict(id="I-29", dzial="I", zakres=["D","E"], podstawa="BHP2019",
  pytanie="Co zrobić, gdy w trakcie pracy okaże się, że zakres prac wykracza poza polecenie?",
  odp=["Przerwać pracę i uzyskać nowe lub zmienione polecenie",
       "Wykonać dodatkowe prace i odnotować to po fakcie",
       "Kontynuować, jeżeli zgodzi się kierujący zespołem",
       "Zgłosić to dopiero na koniec zmiany"],
  ok=0,
  wyj="Polecenie określa zakres pracy, a wyjście poza niego oznacza pracę bez zabezpieczeń przewidzianych dla nowych czynności."),

 dict(id="I-30", dzial="I", zakres=["D"], podstawa="BHP2019",
  pytanie="Co powinna zawierać organizacja pracy przy urządzeniach energetycznych ustalona przez prowadzącego eksploatację?",
  odp=["Wykaz prac na polecenie, wykaz osób upoważnionych oraz zasady łączenia funkcji",
       "Wyłącznie listę pracowników",
       "Wyłącznie harmonogram przeglądów",
       "Wyłącznie schemat zasilania"],
  ok=0,
  wyj="To dokument, na który komisja często pyta osoby dozoru. Bez wykazów i zasad nie da się prawidłowo wydawać poleceń."),

 dict(id="I-31", dzial="I", zakres=["D","E"], podstawa="BHP2019",
  pytanie="Jak należy postąpić przed przystąpieniem do pracy przy urządzeniu zasilanym z dwóch stron?",
  odp=["Wyłączyć i zabezpieczyć zasilanie ze WSZYSTKICH stron, a brak napięcia sprawdzić po każdej",
       "Wyłączyć zasilanie podstawowe, rezerwowe wystarczy oznaczyć",
       "Wyłączyć zasilanie po jednej stronie i uziemić",
       "Wystarczy zgłoszenie do dyspozytora"],
  ok=0,
  wyj="Pominięcie zasilania rezerwowego, agregatu albo instalacji fotowoltaicznej to jedna z najczęstszych przyczyn wypadków porażeniowych."),

 dict(id="I-32", dzial="I", zakres=["D"], podstawa="BHP2019",
  pytanie="Czy polecenie ustne wymaga odnotowania?",
  odp=["Tak, powinno być odnotowane w sposób ustalony u prowadzącego eksploatację",
       "Nie, polecenie ustne nie wymaga żadnego śladu",
       "Tak, ale tylko przy pracach powyżej 1 kV",
       "Tylko wtedy, gdy praca trwa dłużej niż zmiana"],
  ok=0,
  wyj="Odnotowanie pozwala odtworzyć, kto i na co pozwolił. Brak śladu jest problemem przy ustalaniu odpowiedzialności po zdarzeniu."),

 dict(id="I-33", dzial="I", zakres=["D"], podstawa="BHP1997",
  pytanie="Kiedy pracodawca ma obowiązek zapewnić środki ochrony indywidualnej?",
  odp=["Gdy nie da się uniknąć zagrożenia ani ograniczyć go środkami ochrony zbiorowej",
       "Zawsze, niezależnie od środków zbiorowych",
       "Tylko na wyraźne żądanie pracownika",
       "Wyłącznie przy pracy na wysokości"],
  ok=0,
  wyj="Środki indywidualne są ostatnie w hierarchii. Najpierw eliminacja zagrożenia, potem ochrona zbiorowa, potem organizacja pracy."),

 dict(id="I-34", dzial="I", zakres=["D","E"], podstawa="BHP2019",
  pytanie="Jakie warunki musi spełniać sprzęt ochronny używany przy pracach elektrycznych?",
  odp=["Musi mieć aktualne badania okresowe i być sprawny technicznie",
       "Wystarczy, że jest nowy",
       "Wystarczy oznaczenie napięcia znamionowego",
       "Nie podlega żadnym badaniom"],
  ok=0,
  wyj="Rękawice i drążki izolacyjne podlegają okresowym badaniom napięciowym. Sprzęt po terminie badań traktuje się jak niesprawny."),

 dict(id="I-35", dzial="I", zakres=["D"], podstawa="PE",
  pytanie="Kto ustala terminy oględzin, przeglądów i badań urządzeń energetycznych?",
  odp=["Prowadzący eksploatację, z uwzględnieniem wymagań producenta i przepisów",
       "Wyłącznie producent urządzenia",
       "Urząd Dozoru Technicznego",
       "Nikt, terminy są dowolne"],
  ok=0,
  wyj="Instrukcja eksploatacji określa te terminy, a osoba dozoru pilnuje ich dotrzymania i zatwierdza protokoły."),

 dict(id="I-36", dzial="I", zakres=["D"], podstawa="BHP2019",
  pytanie="Co oznacza pojęcie strefy niebezpiecznej przy urządzeniach elektroenergetycznych?",
  odp=["Przestrzeń wokół części czynnych, w której zbliżenie grozi porażeniem",
       "Cały teren zakładu",
       "Pomieszczenie rozdzielni",
       "Obszar oznaczony taśmą, niezależnie od napięcia"],
  ok=0,
  wyj="Wymiary strefy zależą od napięcia — im wyższe, tym większa odległość bezpieczna. Przy urządzeniach do 1 kV jest ona niewielka, ale istnieje."),
]
