# -*- coding: utf-8 -*-
"""Budowa i eksploatacja urzadzen do 1 kV — aparatura, kable, silniki,
rozdzielnice, oswietlenie, kompensacja mocy biernej."""

P = [
 dict(id="II-25", dzial="II", zakres=["D","E"], podstawa="PN60364",
  pytanie="Jaką funkcję pełni wyłącznik nadprądowy typu B w instalacji mieszkaniowej?",
  odp=["Chroni przewody przed przeciążeniem i zwarciem, wyzwalając magnetycznie przy 3–5 krotności prądu znamionowego",
       "Chroni człowieka przed porażeniem prądem dotykowym",
       "Ogranicza przepięcia atmosferyczne",
       "Kompensuje moc bierną obwodu"],
  ok=0,
  wyj="Charakterystyka B jest właściwa dla obwodów odbiorczych bez dużych prądów rozruchowych. Do silników stosuje się C lub D."),

 dict(id="II-26", dzial="II", zakres=["D"], podstawa="PN60364",
  pytanie="Co oznacza selektywność zabezpieczeń?",
  odp=["Zadziałanie wyłącznie zabezpieczenia najbliższego miejscu zwarcia, bez wyłączania nadrzędnych",
       "Dobór zabezpieczeń o tej samej charakterystyce w całej instalacji",
       "Jednoczesne zadziałanie wszystkich zabezpieczeń w torze",
       "Możliwość wyboru zabezpieczenia przez użytkownika"],
  ok=0,
  wyj="Brak selektywności powoduje, że zwarcie w jednym obwodzie gasi cały budynek. Uzyskuje się ją przez różnicę prądów znamionowych i czasów zadziałania."),

 dict(id="II-27", dzial="II", zakres=["D","E"], podstawa="PN60364",
  pytanie="Jaki przekrój ma mieć przewód ochronny PE wykonany z tego samego materiału co przewód fazowy o przekroju 10 mm²?",
  odp=["10 mm²", "4 mm²", "6 mm²", "16 mm²"],
  ok=0,
  wyj="Do 16 mm² przewód ochronny ma przekrój równy fazowemu. Od 16 do 35 mm² wystarczy 16 mm², powyżej połowa przekroju fazowego."),

 dict(id="IV-17", dzial="IV", zakres=["D","E"], podstawa="PN60364",
  pytanie="Jaką najmniejszą rezystancję izolacji musi mieć obwód odbiorczy na napięcie 230/400 V?",
  odp=["1 MΩ przy napięciu pomiarowym 500 V DC",
       "0,5 MΩ przy 250 V DC",
       "10 MΩ przy 1000 V DC",
       "100 kΩ przy 500 V DC"],
  ok=0,
  wyj="Dla obwodów SELV i PELV wymaga się 0,5 MΩ przy 250 V, a powyżej 500 V aż 1 MΩ przy 1000 V."),

 dict(id="IV-18", dzial="IV", zakres=["D"], podstawa="PN60364",
  pytanie="Dlaczego przed pomiarem rezystancji izolacji trzeba odłączyć odbiorniki elektroniczne?",
  odp=["Bo napięcie probiercze rzędu setek woltów może je uszkodzić",
       "Bo zafałszują wynik w stronę zbyt wysokiej rezystancji",
       "Bo pomiar trwałby zbyt długo",
       "Nie trzeba ich odłączać"],
  ok=0,
  wyj="Dodatkowo urządzenia z filtrami przeciwzakłóceniowymi zaniżają wynik, bo ich kondensatory łączą fazę z ochronnym."),

 dict(id="IV-19", dzial="IV", zakres=["D","E"], podstawa="PN60364",
  pytanie="Jaki prąd zadziałania sprawdza się przy badaniu wyłącznika różnicowoprądowego 30 mA?",
  odp=["Musi zadziałać w przedziale od 15 do 30 mA",
       "Musi zadziałać dokładnie przy 30 mA",
       "Musi zadziałać poniżej 10 mA",
       "Prąd zadziałania nie podlega sprawdzeniu"],
  ok=0,
  wyj="Dolna granica to połowa prądu znamionowego różnicowego. Sprawdza się też czas wyłączenia, który przy prądzie znamionowym nie może przekroczyć 300 ms."),

 dict(id="IV-20", dzial="IV", zakres=["D"], podstawa="PN60364",
  pytanie="Co oznacza dodatni wynik próby ciągłości przewodów ochronnych?",
  odp=["Zmierzona rezystancja połączenia jest niska, rzędu pojedynczych omów",
       "Rezystancja przekracza 1 MΩ",
       "Przewód ochronny jest odłączony od uziomu",
       "Napięcie dotykowe wynosi zero"],
  ok=0,
  wyj="Próbę wykonuje się prądem co najmniej 200 mA przy napięciu 4–24 V. Wysoka rezystancja oznacza przerwany albo skorodowany styk."),

 dict(id="I-37", dzial="I", zakres=["D","E"], podstawa="BHP2019",
  pytanie="Jakie warunki musi spełniać drabina używana przy pracach elektrycznych?",
  odp=["Powinna być wykonana z materiału nieprzewodzącego lub zabezpieczona przed przewodzeniem",
       "Musi być metalowa, żeby zapewnić uziemienie",
       "Rodzaj materiału nie ma znaczenia",
       "Musi mieć co najmniej 5 m długości"],
  ok=0,
  wyj="Drabiny z włókna szklanego są standardem w energetyce. Metalowa drabina w pobliżu urządzeń pod napięciem to droga prądu do ziemi przez ciało."),

 dict(id="I-38", dzial="I", zakres=["D"], podstawa="BHP2019",
  pytanie="Kiedy dopuszcza się pracę na wysokości bez środków ochrony indywidualnej przed upadkiem?",
  odp=["Gdy stanowisko jest zabezpieczone balustradą o wysokości 1,1 m z krawężnikiem",
       "Nigdy, szelki są zawsze obowiązkowe",
       "Gdy praca trwa krócej niż 15 minut",
       "Gdy pracownik ma odpowiednie doświadczenie"],
  ok=0,
  wyj="Ochrona zbiorowa ma pierwszeństwo przed indywidualną. Balustrada wymaga też poprzeczki w połowie wysokości."),

 dict(id="I-39", dzial="I", zakres=["D"], podstawa="BHP2019",
  pytanie="Co powinno zawierać stanowiskowe szkolenie wstępne elektryka?",
  odp=["Zapoznanie z zagrożeniami na konkretnym stanowisku i bezpiecznymi metodami pracy, zakończone sprawdzeniem wiedzy",
       "Wyłącznie omówienie przepisów przeciwpożarowych",
       "Wyłącznie pokaz gaśnic",
       "Wyłącznie podpis na liście obecności"],
  ok=0,
  wyj="Instruktaż stanowiskowy prowadzi bezpośredni przełożony. Fakt jego odbycia potwierdza się na piśmie w karcie szkolenia."),

 dict(id="I-40", dzial="I", zakres=["D","E"], podstawa="BHP2019",
  pytanie="Jak należy oznakować miejsce pracy w rozdzielnicy, w której sąsiednie pola pozostają pod napięciem?",
  odp=["Ogrodzić strefę pracy i oznaczyć pola sąsiednie tablicami ostrzegawczymi",
       "Wystarczy ustne uprzedzenie zespołu",
       "Oznakowanie nie jest potrzebne, jeśli pracuje jedna osoba",
       "Wyłączyć oświetlenie w polach sąsiednich"],
  ok=0,
  wyj="Najczęstszą przyczyną wypadków w rozdzielnicach jest wejście w niewłaściwe pole. Ogrodzenie i tablice fizycznie ograniczają tę pomyłkę."),

 dict(id="I-41", dzial="I", zakres=["D"], podstawa="BHP2019",
  pytanie="Kto decyduje o przerwaniu pracy w razie stwierdzenia zagrożenia?",
  odp=["Każdy członek zespołu może wstrzymać pracę, a kierujący zespołem ma obowiązek to zrobić",
       "Wyłącznie poleceniodawca",
       "Wyłącznie koordynator",
       "Wyłącznie inspektor pracy"],
  ok=0,
  wyj="Pracownik ma prawo powstrzymać się od pracy zagrażającej życiu, zawiadamiając przełożonego. Nie traci za to prawa do wynagrodzenia."),

 dict(id="V-07", dzial="V", zakres=["D"], podstawa="PN60364",
  pytanie="Jak wykonuje się układ uziemienia agregatu zasilającego wydzieloną instalację jako źródło niezależne?",
  odp=["Punkt neutralny generatora uziemia się, tworząc lokalny układ TN lub TT",
       "Punkt neutralny pozostawia się izolowany i nie stosuje zabezpieczeń",
       "Uziemia się wyłącznie obudowę, bez punktu neutralnego",
       "Nie stosuje się uziemienia, bo agregat jest przenośny"],
  ok=0,
  wyj="Bez uziemionego punktu odniesienia zabezpieczenia nadprądowe nie zadziałają przy pierwszym doziemieniu. Dla małych agregatów przenośnych stosuje się alternatywnie separację elektryczną."),

 dict(id="VII-06", dzial="VII", zakres=["D"], podstawa="BHP2019",
  pytanie="Jakie zagrożenie stwarzają urządzenia grzejne indukcyjne dużej mocy?",
  odp=["Silne pole elektromagnetyczne, groźne zwłaszcza dla osób z wszczepionymi implantami",
       "Wyłącznie zagrożenie oparzeniem",
       "Zagrożenie wybuchem wodoru",
       "Nie stwarzają żadnych szczególnych zagrożeń"],
  ok=0,
  wyj="Wokół wzbudników wyznacza się strefy ochronne pola elektromagnetycznego. Osoby z rozrusznikiem serca nie mogą tam przebywać."),

 dict(id="VII-07", dzial="VII", zakres=["D","E"], podstawa="BHP2019",
  pytanie="Co należy zrobić przed wejściem do wnętrza pieca elektrycznego w celu wykonania prac remontowych?",
  odp=["Odłączyć zasilanie, zabezpieczyć przed załączeniem, odczekać na ostygnięcie i sprawdzić atmosferę wewnątrz",
       "Wystarczy wyłączyć zasilanie",
       "Wystarczy odczekać do ostygnięcia",
       "Wejść w asyście drugiej osoby, bez dodatkowych czynności"],
  ok=0,
  wyj="Wnętrze pieca jest przestrzenią zamkniętą. Obok zagrożenia elektrycznego i termicznego występuje niedobór tlenu, a praca wymaga asekuracji z zewnątrz."),

 dict(id="IX-05", dzial="IX", zakres=["D"], podstawa="BHP2019",
  pytanie="Jaka jest zasada wykonywania prac przy sieci trakcyjnej wyłączonej spod napięcia?",
  odp=["Po wyłączeniu zakłada się uziemiacze przenośne po obu stronach miejsca pracy",
       "Wystarczy wyłączenie w podstacji",
       "Uziemia się wyłącznie od strony podstacji",
       "Uziemienie jest zbędne przy prądzie stałym"],
  ok=0,
  wyj="Sieć trakcyjna może zostać zasilona z drugiej strony odcinka albo od pojazdu z odzyskiem energii. Uziemienie obustronne zamyka obie te drogi."),

 dict(id="IX-06", dzial="IX", zakres=["D"], podstawa="BHP2019",
  pytanie="Jaki jest minimalny bezpieczny odstęp od nieosłoniętej sieci trakcyjnej 3 kV DC pod napięciem?",
  odp=["Nie wolno się zbliżać na odległość mniejszą niż wyznaczona w instrukcji, typowo 1,4 m wraz z narzędziami",
       "0,1 m", "5 cm", "Dowolny, bo 3 kV to napięcie bezpieczne"],
  ok=0,
  wyj="Odstęp obejmuje także trzymane narzędzia i materiały. Przy pracy z podnośnika trzeba uwzględnić jego wychylenia."),

 dict(id="X-16", dzial="X", zakres=["D"], podstawa="PE",
  pytanie="Co powinna zawierać instrukcja eksploatacji urządzenia elektroenergetycznego?",
  odp=["Charakterystykę urządzenia, zasady obsługi, czynności przy zakłóceniach i wymagania bhp",
       "Wyłącznie schemat ideowy",
       "Wyłącznie wykaz części zamiennych",
       "Wyłącznie dane kontaktowe producenta"],
  ok=0,
  wyj="Instrukcję zatwierdza pracodawca, a jej znajomość jest warunkiem dopuszczenia do obsługi. To dokument stanowiskowy, nie katalogowy."),

 dict(id="X-17", dzial="X", zakres=["D"], podstawa="PE",
  pytanie="Jak długo należy przechowywać protokoły z pomiarów ochronnych?",
  odp=["Co najmniej do czasu wykonania kolejnych pomiarów, a w praktyce przez cały okres eksploatacji urządzenia",
       "30 dni", "Nie ma obowiązku przechowywania", "Dokładnie 12 miesięcy"],
  ok=0,
  wyj="Protokół jest dowodem należytej staranności po awarii albo wypadku. Porównanie kolejnych pomiarów pokazuje też trend degradacji izolacji."),

 dict(id="X-18", dzial="X", zakres=["D"], podstawa="KWAL2022",
  pytanie="Czy świadectwo kwalifikacyjne D uprawnia do wykonywania prac montażowych przy urządzeniach?",
  odp=["Nie, prace wykonawcze wymagają świadectwa w zakresie eksploatacji",
       "Tak, dozór obejmuje wszystkie czynności",
       "Tak, ale wyłącznie do 1 kV",
       "Tak, pod warunkiem nadzoru innej osoby"],
  ok=0,
  wyj="Zakres D obejmuje kierowanie, nadzór, odbiory i wydawanie poleceń. Żeby samodzielnie wykonywać prace, trzeba mieć także zakres E."),
]
