# -*- coding: utf-8 -*-
"""Dzialy V-X — zespoly pradotworcze, pomoc przedlekarska, elektrotermia,
fotowoltaika, trakcja, przepisy i kwalifikacje."""

P = [
 # ---------------- V. ZESPOLY PRADOTWORCZE ----------------
 dict(id="V-01", dzial="V", zakres=["D","E"], podstawa="PN60364",
  pytanie="Jakie zabezpieczenie jest konieczne przy zasilaniu obiektu z agregatu prądotwórczego jako zasilania rezerwowego?",
  odp=["Blokada uniemożliwiająca jednoczesne załączenie sieci i agregatu",
       "Dodatkowy wyłącznik nadprądowy w obwodzie agregatu",
       "Wyłącznie oznaczenie tabliczką ostrzegawczą",
       "Kompensator mocy biernej"],
  ok=0,
  wyj="Bez blokady wzajemnej (mechanicznej lub elektrycznej) agregat może podać napięcie do sieci, zagrażając osobom pracującym na linii. To klasyczne pytanie dozorowe."),

 dict(id="V-02", dzial="V", zakres=["D"], podstawa="BHP2019",
  pytanie="Dlaczego agregat prądotwórczy przy pracy wewnątrz pomieszczeń stanowi szczególne zagrożenie?",
  odp=["Wydziela spaliny zawierające tlenek węgla, co grozi zatruciem",
       "Wytwarza napięcie wyższe niż znamionowe",
       "Nie może być uziemiony",
       "Zawsze pracuje w układzie IT"],
  ok=0,
  wyj="Poza zagrożeniem porażeniem dochodzi zagrożenie zatruciem tlenkiem węgla i pożarem od paliwa. Agregaty spalinowe wymagają wentylacji lub pracy na zewnątrz."),

 dict(id="V-03", dzial="V", zakres=["D","E"], podstawa="PN60364",
  pytanie="W jakim układzie sieci pracuje zwykle przenośny agregat prądotwórczy zasilający pojedyncze odbiorniki?",
  odp=["W układzie IT z separacją, z kontrolą stanu izolacji lub z uziemionym punktem neutralnym w zależności od wykonania",
       "Zawsze w układzie TN-C",
       "Zawsze w układzie TT z uziomem o rezystancji poniżej 1 Ω",
       "Zawsze w układzie TN-S z PEN"],
  ok=0,
  wyj="Małe agregaty często pracują jako źródło separowane. Sposób ochrony zależy od wykonania agregatu i powinien wynikać z instrukcji producenta."),

 dict(id="V-04", dzial="V", zakres=["D"], podstawa="BHP2019",
  pytanie="Co należy sprawdzić przed uruchomieniem zespołu prądotwórczego po dłuższym postoju?",
  odp=["Stan techniczny, poziom płynów, szczelność instalacji paliwowej, stan połączeń ochronnych i skuteczność blokad",
       "Wyłącznie poziom paliwa",
       "Wyłącznie napięcie na wyjściu",
       "Wyłącznie datę ostatniego przeglądu"],
  ok=0,
  wyj="Uruchomienie po postoju wymaga oględzin całości: mechaniki, paliwa, instalacji elektrycznej, uziemienia i blokad. Osoba dozoru dopuszcza urządzenie do ruchu."),

 # ---------------- VI. POMOC PRZEDLEKARSKA ----------------
 dict(id="VI-01", dzial="VI", zakres=["D","E"], podstawa="KP",
  pytanie="Jaka jest pierwsza czynność przy ratowaniu osoby porażonej prądem elektrycznym?",
  odp=["Uwolnienie porażonego spod działania prądu przy zachowaniu własnego bezpieczeństwa",
       "Natychmiastowe rozpoczęcie uciśnięć klatki piersiowej",
       "Wezwanie pogotowia i oczekiwanie na przyjazd",
       "Sprawdzenie tętna na tętnicy szyjnej"],
  ok=0,
  wyj="Dopóki poszkodowany pozostaje w obwodzie, ratownik sam jest zagrożony. Najpierw odłącza się napięcie lub odciąga poszkodowanego materiałem izolacyjnym, dopiero potem ocenia stan."),

 dict(id="VI-02", dzial="VI", zakres=["D","E"], podstawa="KP",
  pytanie="Jaki jest prawidłowy stosunek uciśnięć klatki piersiowej do oddechów ratowniczych u osoby dorosłej?",
  odp=["30 uciśnięć do 2 oddechów", "15 uciśnięć do 2 oddechów", "5 uciśnięć do 1 oddechu", "10 uciśnięć do 2 oddechów"],
  ok=0,
  wyj="Standard resuscytacji u dorosłych to 30:2, z częstością 100–120 uciśnięć na minutę i głębokością 5–6 cm."),

 dict(id="VI-03", dzial="VI", zakres=["D","E"], podstawa="KP",
  pytanie="Jaki numer alarmowy należy wybrać w razie wypadku?",
  odp=["112 lub 999", "997", "998", "991"],
  ok=0,
  wyj="112 to numer alarmowy ogólny, 999 to pogotowie ratunkowe. 998 to straż pożarna, 997 policja, 991 pogotowie energetyczne."),

 dict(id="VI-04", dzial="VI", zakres=["D","E"], podstawa="KP",
  pytanie="Czym charakteryzuje się działanie prądu przemiennego o częstotliwości 50 Hz na organizm człowieka?",
  odp=["Jest szczególnie groźne, bo sprzyja migotaniu komór serca",
       "Jest mniej groźne niż prąd stały o tej samej wartości",
       "Powoduje wyłącznie oparzenia zewnętrzne",
       "Nie wpływa na pracę serca"],
  ok=0,
  wyj="Częstotliwość 50 Hz jest najbardziej niebezpieczna dla serca — sprzyja migotaniu komór. Prąd stały przy tej samej wartości jest mniej groźny pod tym względem."),

 dict(id="VI-05", dzial="VI", zakres=["D"], podstawa="KP",
  pytanie="Jak postąpić z osobą porażoną prądem, która jest nieprzytomna, ale oddycha prawidłowo?",
  odp=["Ułożyć w pozycji bocznej bezpiecznej i kontrolować oddech do przyjazdu pogotowia",
       "Posadzić i podać płyny",
       "Rozpocząć resuscytację",
       "Pozostawić w pozycji zastanej i czekać"],
  ok=0,
  wyj="Pozycja boczna bezpieczna chroni drogi oddechowe przed zachłyśnięciem. Oddech kontroluje się ciągle, bo może ustać."),

 dict(id="VI-06", dzial="VI", zakres=["D","E"], podstawa="KP",
  pytanie="Jak należy postępować przy oparzeniu łukiem elektrycznym?",
  odp=["Schładzać ranę czystą, chłodną wodą i osłonić jałowym opatrunkiem, nie usuwając przywartej odzieży",
       "Posmarować tłuszczem i zabandażować",
       "Przekłuć powstałe pęcherze i zdezynfekować spirytusem",
       "Zostawić bez opatrunku do przyjazdu pogotowia"],
  ok=0,
  wyj="Schładzanie ogranicza głębokość oparzenia. Nie stosuje się tłuszczów ani środków domowych, nie przekłuwa pęcherzy i nie odrywa przywartej odzieży."),

 dict(id="VI-07", dzial="VI", zakres=["D"], podstawa="BHP1997",
  pytanie="Jaki obowiązek ma pracodawca w zakresie pierwszej pomocy?",
  odp=["Zapewnić środki do udzielania pierwszej pomocy, wyznaczyć i przeszkolić osoby do jej udzielania oraz zapewnić łączność ze służbami",
       "Wyłącznie zapewnić apteczkę",
       "Wyłącznie przeszkolić służbę BHP",
       "Wyłącznie wywiesić instrukcję udzielania pomocy"],
  ok=0,
  wyj="Obowiązek obejmuje wyposażenie, wyznaczenie i przeszkolenie osób oraz zapewnienie łączności ze służbami ratowniczymi. Apteczka to tylko jeden element."),

 # ---------------- VII. ELEKTROTERMIA I ELEKTROLIZA ----------------
 dict(id="VII-01", dzial="VII", zakres=["D","E"], podstawa="BHP2019",
  pytanie="Jakie dodatkowe zagrożenie występuje przy urządzeniach elektrotermicznych?",
  odp=["Zagrożenie oparzeniem i pożarem od wysokiej temperatury oraz promieniowania cieplnego",
       "Wyłącznie zagrożenie porażeniem prądem",
       "Zagrożenie wybuchem pyłu węglowego",
       "Brak zagrożeń dodatkowych"],
  ok=0,
  wyj="Poza porażeniem dochodzi wysoka temperatura, promieniowanie cieplne, a przy piecach łukowych również hałas i olśnienie. Wymaga to odrębnych środków ochrony."),

 dict(id="VII-02", dzial="VII", zakres=["D"], podstawa="BHP2019",
  pytanie="Jakie szczególne ryzyko wiąże się z instalacjami elektrolizy?",
  odp=["Obecność prądu stałego o dużym natężeniu oraz wydzielanie się gazów, w tym wodoru",
       "Wyłącznie ryzyko przeciążenia sieci",
       "Brak ryzyka porażenia ze względu na prąd stały",
       "Wyłącznie ryzyko korozji konstrukcji"],
  ok=0,
  wyj="W elektrolizie płyną duże prądy stałe, a na elektrodach wydziela się wodór i tlen. Grozi to wybuchem, dlatego wymagana jest wentylacja i kontrola stężeń."),

 dict(id="VII-03", dzial="VII", zakres=["D","E"], podstawa="BHP2019",
  pytanie="Dlaczego przy urządzeniach elektrotermicznych stosuje się osłony i ekrany?",
  odp=["Aby ograniczyć oddziaływanie promieniowania cieplnego i chronić przed dotknięciem elementów gorących",
       "Aby zwiększyć sprawność grzania",
       "Aby ograniczyć pobór mocy biernej",
       "Aby zmniejszyć rezystancję uziemienia"],
  ok=0,
  wyj="Ekrany i osłony to środki ochrony zbiorowej. Chronią przed oparzeniem i nadmiernym obciążeniem cieplnym stanowiska pracy."),

 # ---------------- VIII. FOTOWOLTAIKA I MAGAZYNY ENERGII ----------------
 dict(id="VIII-01", dzial="VIII", zakres=["D","E"], podstawa="PN60364",
  pytanie="Dlaczego instalacja fotowoltaiczna jest szczególnie niebezpieczna podczas prac serwisowych?",
  odp=["Moduły wytwarzają napięcie stałe zawsze, gdy pada na nie światło, i nie da się ich wyłączyć wyłącznikiem po stronie AC",
       "Ponieważ pracuje wyłącznie przy napięciu powyżej 1 kV",
       "Ponieważ nie wymaga uziemienia",
       "Ponieważ napięcie stałe nie jest groźne dla człowieka"],
  ok=0,
  wyj="Wyłączenie falownika nie odłącza napięcia po stronie DC. Strona DC pozostaje pod napięciem tak długo, jak świeci słońce — stąd wyłączniki DC i rozłączniki przy modułach."),

 dict(id="VIII-02", dzial="VIII", zakres=["D"], podstawa="PN60364",
  pytanie="Czemu służy funkcja zabezpieczenia anty-wyspowego w falowniku fotowoltaicznym?",
  odp=["Odłączeniu instalacji od sieci przy zaniku napięcia sieciowego, aby nie zasilać wyłączonej sieci",
       "Ograniczeniu mocy oddawanej do sieci w godzinach szczytu",
       "Ochronie modułów przed przepięciem atmosferycznym",
       "Wyrównaniu napięć między fazami"],
  ok=0,
  wyj="Bez zabezpieczenia anty-wyspowego falownik mógłby podać napięcie na wyłączony odcinek sieci, zagrażając ekipom remontowym. To pytanie chętnie zadawane osobom dozoru."),

 dict(id="VIII-03", dzial="VIII", zakres=["D","E"], podstawa="PN60364",
  pytanie="Jak należy postąpić przy pożarze instalacji fotowoltaicznej?",
  odp=["Powiadomić straż pożarną, wskazać lokalizację wyłącznika i poinformować o obecności napięcia DC",
       "Gasić wodą z bliskiej odległości",
       "Odłączyć wyłącznie stronę AC i uznać instalację za bezpieczną",
       "Zdemontować moduły przed przyjazdem straży"],
  ok=0,
  wyj="Strona DC pozostaje pod napięciem mimo wyłączenia AC. Straż musi wiedzieć o tym oraz o lokalizacji wyłącznika pożarowego i przebiegu tras kablowych."),

 dict(id="VIII-04", dzial="VIII", zakres=["D"], podstawa="BHP2019",
  pytanie="Jakie zagrożenie wiąże się z magazynem energii opartym na ogniwach litowo-jonowych?",
  odp=["Ryzyko niekontrolowanego wzrostu temperatury i pożaru trudnego do ugaszenia, z wydzielaniem toksycznych gazów",
       "Wyłącznie ryzyko rozładowania i utraty pojemności",
       "Brak zagrożeń, bo napięcie jest niskie",
       "Wyłącznie ryzyko przeciążenia sieci"],
  ok=0,
  wyj="Zjawisko ucieczki termicznej powoduje pożar podtrzymujący się samoczynnie. Magazyny wymagają odrębnych warunków lokalizacji, wentylacji i systemów detekcji."),

 dict(id="VIII-05", dzial="VIII", zakres=["D","E"], podstawa="PN60364",
  pytanie="Co oznacza oznaczenie napięcia w obwodzie DC instalacji PV rzędu 600–1000 V?",
  odp=["Jest to napięcie niebezpieczne, wymagające traktowania obwodu jak instalacji pod napięciem",
       "Jest to napięcie bardzo niskie, bezpieczne przy dotyku",
       "Napięcie to występuje wyłącznie przy awarii",
       "Napięcie DC nie stwarza zagrożenia łukiem"],
  ok=0,
  wyj="Napięcia DC w łańcuchach modułów sięgają 1000 V i więcej. Prąd stały utrudnia gaszenie łuku, więc rozłączniki DC muszą być do tego przystosowane."),

 # ---------------- IX. TRAKCJA ELEKTRYCZNA ----------------
 dict(id="IX-01", dzial="IX", zakres=["D","E"], podstawa="BHP2019",
  pytanie="Jakim napięciem zasilana jest sieć trakcyjna kolei w Polsce?",
  odp=["3 kV prądu stałego", "15 kV prądu przemiennego", "25 kV prądu przemiennego", "1,5 kV prądu stałego"],
  ok=0,
  wyj="Polska sieć kolejowa pracuje na 3 kV DC. Tramwaje zasilane są zwykle napięciem 600 lub 750 V DC."),

 dict(id="IX-02", dzial="IX", zakres=["D"], podstawa="BHP2019",
  pytanie="Jakie zagrożenie jest charakterystyczne dla prac w pobliżu sieci trakcyjnej?",
  odp=["Możliwość zbliżenia się na niebezpieczną odległość do części pod napięciem oraz prądy błądzące",
       "Wyłącznie zagrożenie mechaniczne od taboru",
       "Brak zagrożenia, bo napięcie jest stałe",
       "Wyłącznie zagrożenie hałasem"],
  ok=0,
  wyj="Prace przy trakcji wymagają wyłączenia i uziemienia odcinka oraz zachowania odległości bezpiecznych. Prądy błądzące powodują dodatkowo korozję konstrukcji podziemnych."),

 dict(id="IX-03", dzial="IX", zakres=["D","E"], podstawa="BHP2019",
  pytanie="Co należy zrobić przed rozpoczęciem pracy przy wyłączonej sieci trakcyjnej?",
  odp=["Sprawdzić brak napięcia i uziemić odcinek po obu stronach strefy pracy",
       "Wystarczy wyłączyć zasilanie w podstacji",
       "Wystarczy oznaczyć strefę taśmą ostrzegawczą",
       "Wystarczy zgłoszenie do dyżurnego ruchu"],
  ok=0,
  wyj="Uziemienie obustronne chroni przed napięciem indukowanym i przypadkowym podaniem zasilania. Samo wyłączenie w podstacji nie wystarcza."),

 # ---------------- X. PRZEPISY, KWALIFIKACJE, DOKUMENTACJA ----------------
 dict(id="X-01", dzial="X", zakres=["D","E"], podstawa="KWAL2022",
  pytanie="Na jaki okres wydawane jest świadectwo kwalifikacyjne?",
  odp=["5 lat", "3 lata", "10 lat", "Bezterminowo"],
  ok=0,
  wyj="Świadectwo kwalifikacyjne jest ważne 5 lat od dnia wydania. Po tym okresie wymagane jest ponowne przystąpienie do egzaminu."),

 dict(id="X-02", dzial="X", zakres=["D","E"], podstawa="KWAL2022",
  pytanie="Ile wynosi opłata za jeden egzamin kwalifikacyjny?",
  odp=["10% minimalnego wynagrodzenia za pracę obowiązującego w dniu złożenia wniosku",
       "5% minimalnego wynagrodzenia",
       "Kwota stała 300 zł niezależnie od roku",
       "20% przeciętnego wynagrodzenia"],
  ok=0,
  wyj="Opłata to 10% minimalnego wynagrodzenia i pobierana jest osobno za każdy rodzaj uprawnień — oddzielnie za dozór i oddzielnie za eksploatację."),

 dict(id="X-03", dzial="X", zakres=["D"], podstawa="KWAL2022",
  pytanie="Czym różni się zakres uprawnień dozoru od uprawnień eksploatacji?",
  odp=["Dozór obejmuje kierowanie i nadzór nad czynnościami oraz sprawowanie nadzoru nad eksploatacją, eksploatacja — wykonywanie tych czynności",
       "Dozór dotyczy urządzeń powyżej 1 kV, eksploatacja poniżej",
       "Dozór dotyczy wyłącznie dokumentacji, eksploatacja wyłącznie pomiarów",
       "Nie ma różnicy, to te same uprawnienia"],
  ok=0,
  wyj="Świadectwo D uprawnia do kierowania czynnościami i nadzoru, E do ich wykonywania. Posiadanie D nie uprawnia automatycznie do samodzielnego wykonywania prac."),

 dict(id="X-04", dzial="X", zakres=["D","E"], podstawa="KWAL2022",
  pytanie="Jakie czynności obejmuje pojęcie eksploatacji urządzeń w rozumieniu przepisów?",
  odp=["Obsługę, konserwację, remonty, montaż oraz prace kontrolno-pomiarowe",
       "Wyłącznie obsługę i konserwację",
       "Wyłącznie montaż i remonty",
       "Wyłącznie prace kontrolno-pomiarowe"],
  ok=0,
  wyj="Zakres świadectwa wskazuje, które z tych rodzajów czynności obejmuje. Warto sprawdzić wpisy na własnym świadectwie, bo brak wpisu o pomiarach wyklucza ich wykonywanie."),

 dict(id="X-05", dzial="X", zakres=["D"], podstawa="PE",
  pytanie="Kto powołuje komisje kwalifikacyjne przeprowadzające egzaminy?",
  odp=["Prezes Urzędu Regulacji Energetyki",
       "Minister właściwy do spraw pracy",
       "Wojewoda właściwy dla siedziby jednostki",
       "Stowarzyszenie Elektryków Polskich samodzielnie"],
  ok=0,
  wyj="Komisje kwalifikacyjne powołuje Prezes URE. Stowarzyszenia i jednostki organizacyjne mogą jedynie wnioskować o ich powołanie."),

 dict(id="X-06", dzial="X", zakres=["D"], podstawa="PB",
  pytanie="Kto prowadzi książkę obiektu budowlanego?",
  odp=["Właściciel lub zarządca obiektu",
       "Projektant obiektu",
       "Kierownik budowy",
       "Inspektor nadzoru inwestorskiego"],
  ok=0,
  wyj="Właściciel lub zarządca prowadzi książkę obiektu i wpisuje do niej wyniki kontroli okresowych, w tym kontroli instalacji elektrycznej."),

 dict(id="X-07", dzial="X", zakres=["D","E"], podstawa="BHP2019",
  pytanie="Jakie dokumenty powinny być dostępne w miejscu eksploatacji urządzeń energetycznych?",
  odp=["Instrukcje eksploatacji, dokumentacja techniczna, schematy oraz protokoły z badań i pomiarów",
       "Wyłącznie schemat jednokreskowy",
       "Wyłącznie świadectwa kwalifikacyjne pracowników",
       "Wyłącznie karty gwarancyjne urządzeń"],
  ok=0,
  wyj="Komplet dokumentacji eksploatacyjnej to obowiązek prowadzącego eksploatację i jeden z pierwszych elementów sprawdzanych przy kontroli."),

 dict(id="X-08", dzial="X", zakres=["D"], podstawa="PE",
  pytanie="Czy osoba posiadająca wyłącznie świadectwo D może samodzielnie wykonać naprawę rozdzielnicy?",
  odp=["Nie, świadectwo D uprawnia do nadzoru, a nie do wykonywania prac",
       "Tak, uprawnienia D zawierają w sobie uprawnienia E",
       "Tak, jeżeli praca trwa krócej niż godzinę",
       "Tak, pod warunkiem zgłoszenia do URE"],
  ok=0,
  wyj="D i E to odrębne świadectwa. Do samodzielnego wykonywania prac potrzebne jest E — to najczęstsze nieporozumienie przy wyborze zakresu egzaminu."),

 dict(id="X-09", dzial="X", zakres=["D"], podstawa="KP",
  pytanie="Czy pracownik ma prawo powstrzymać się od wykonywania pracy zagrażającej jego życiu?",
  odp=["Tak, po uprzednim zawiadomieniu przełożonego, zachowując prawo do wynagrodzenia",
       "Nie, polecenie przełożonego jest wiążące",
       "Tak, ale traci prawo do wynagrodzenia za ten czas",
       "Tylko za zgodą inspektora pracy"],
  ok=0,
  wyj="Kodeks pracy daje prawo powstrzymania się od pracy, gdy warunki nie odpowiadają przepisom BHP i stwarzają bezpośrednie zagrożenie. Osoba dozoru musi to prawo znać i respektować."),

 dict(id="X-10", dzial="X", zakres=["D","E"], podstawa="KWAL2022",
  pytanie="W jakiej formie przeprowadzany jest egzamin kwalifikacyjny?",
  odp=["W formie ustnej przed komisją kwalifikacyjną",
       "Wyłącznie w formie testu jednokrotnego wyboru",
       "W formie praktycznej na stanowisku pracy",
       "W formie pisemnej pracy problemowej"],
  ok=0,
  wyj="Egzamin ma formę ustną. Dlatego przygotowanie polega na umiejętności wytłumaczenia procedury, a nie na rozpoznaniu poprawnej odpowiedzi z listy."),
]
