# -*- coding: utf-8 -*-
"""Uzupelnienie dzialow cienkich: strefy Ex, zespoly pradotworcze,
pomoc przedlekarska, trakcja, plus pytania sytuacyjne dla dozoru."""

P = [
 dict(id="III-10", dzial="III", zakres=["D","E"], podstawa="ATEX",
  pytanie="Co oznacza rodzaj budowy przeciwwybuchowej „d”?",
  odp=["Osłona ognioszczelna, wytrzymująca wybuch wewnątrz i nieprzenosząca go na zewnątrz",
       "Osłona zwiększonego bezpieczeństwa",
       "Iskrobezpieczeństwo",
       "Osłona olejowa"],
  ok=0,
  wyj="Ognioszczelność uzyskuje się przez szczeliny gaszące płomień. Dlatego nie wolno dorabiać otworów ani spiłowywać kołnierzy takiej obudowy."),

 dict(id="III-11", dzial="III", zakres=["D"], podstawa="ATEX",
  pytanie="Na czym polega ochrona typu iskrobezpiecznego „i”?",
  odp=["Na ograniczeniu energii obwodu poniżej wartości zdolnej zapalić mieszaninę wybuchową",
       "Na hermetycznym zamknięciu obwodu",
       "Na zalaniu obwodu masą izolacyjną",
       "Na nadciśnieniu gazu obojętnego w obudowie"],
  ok=0,
  wyj="Obwód iskrobezpieczny wolno serwisować pod napięciem w strefie zagrożonej. Wymaga jednak zasilania przez certyfikowaną barierę i osobnych, oznaczonych na niebiesko przewodów."),

 dict(id="III-12", dzial="III", zakres=["D"], podstawa="ATEX",
  pytanie="Kto sporządza dokument zabezpieczenia przed wybuchem?",
  odp=["Pracodawca, przed rozpoczęciem pracy w przestrzeni zagrożonej wybuchem",
       "Producent urządzeń", "Jednostka notyfikowana", "Inspektor pracy"],
  ok=0,
  wyj="Dokument zawiera ocenę ryzyka wybuchu, wykaz stref i środki ochronne. Aktualizuje się go przy każdej istotnej zmianie w instalacji."),

 dict(id="III-13", dzial="III", zakres=["D","E"], podstawa="ATEX",
  pytanie="Czym jest klasa temperaturowa T4 urządzenia przeciwwybuchowego?",
  odp=["Maksymalna temperatura powierzchni urządzenia nie przekracza 135 °C",
       "Urządzenie pracuje w otoczeniu do 40 °C",
       "Czwarty stopień odporności na przegrzanie",
       "Temperatura zapłonu gazu wynosi 135 °C"],
  ok=0,
  wyj="Temperatura powierzchni musi być niższa od temperatury samozapłonu obecnego gazu. T1 to 450 °C, T6 zaledwie 85 °C."),

 dict(id="V-08", dzial="V", zakres=["D","E"], podstawa="BHP2019",
  pytanie="Dlaczego agregat prądotwórczy spalinowy nie może pracować wewnątrz pomieszczenia?",
  odp=["Ze względu na tlenek węgla w spalinach, bezwonny i śmiertelnie trujący",
       "Ze względu na zbyt wysoką wilgotność",
       "Ze względu na drgania uszkadzające konstrukcję",
       "Może pracować, jeśli ma zamknięty rozrusznik"],
  ok=0,
  wyj="Zatrucia czadem od agregatów zdarzają się regularnie po wichurach i przerwach w zasilaniu. Praca w pomieszczeniu wymaga odprowadzenia spalin na zewnątrz."),

 dict(id="V-09", dzial="V", zakres=["D"], podstawa="PE",
  pytanie="Jak często należy próbnie uruchamiać agregat rezerwowy zasilania awaryjnego?",
  odp=["Zgodnie z instrukcją eksploatacji, zwykle nie rzadziej niż raz w miesiącu, pod obciążeniem",
       "Raz na pięć lat", "Wyłącznie przy rzeczywistym zaniku zasilania", "Raz na dwa lata"],
  ok=0,
  wyj="Próba bez obciążenia nie wykrywa najczęstszych usterek. Wyniki prób wpisuje się do dokumentacji eksploatacyjnej."),

 dict(id="V-10", dzial="V", zakres=["D"], podstawa="PN60364",
  pytanie="Co powinien zapewniać samoczynny układ SZR?",
  odp=["Przełączenie na zasilanie rezerwowe po zaniku podstawowego, bez możliwości równoległej pracy źródeł",
       "Równoległą pracę sieci i agregatu na stałe",
       "Wyłączenie wszystkich odbiorników przy zaniku zasilania",
       "Kompensację mocy biernej"],
  ok=0,
  wyj="Praca równoległa wymagałaby synchronizacji i osobnych zabezpieczeń. Zwykły SZR realizuje przełączanie wzajemnie wykluczające."),

 dict(id="VI-12", dzial="VI", zakres=["D","E"], podstawa="KP",
  pytanie="Jak postąpić z osobą porażoną prądem, która jest przytomna i wygląda dobrze?",
  odp=["Zapewnić opiekę medyczną, bo zaburzenia rytmu serca mogą wystąpić z opóźnieniem",
       "Odesłać do pracy, skoro czuje się dobrze",
       "Podać coś do picia i obserwować przez 10 minut",
       "Skierować do lekarza dopiero przy dolegliwościach"],
  ok=0,
  wyj="Po przepływie prądu przez klatkę piersiową zaleca się badanie EKG. Występują też późne oparzenia wewnętrzne niewidoczne na skórze."),

 dict(id="VI-13", dzial="VI", zakres=["D","E"], podstawa="KP",
  pytanie="Jak zaopatrzyć oparzenie łukiem elektrycznym?",
  odp=["Schładzać czystą, chłodną wodą i osłonić jałowym opatrunkiem, nie usuwając przywartej odzieży",
       "Posmarować tłuszczem i zabandażować ciasno",
       "Przekłuć pęcherze i zdezynfekować spirytusem",
       "Owinąć szczelnie folią bez schładzania"],
  ok=0,
  wyj="Schładzanie ogranicza głębokość urazu, ale u rozległych oparzeń trzeba uważać na wychłodzenie. Tłuszcze i odrywanie odzieży pogłębiają uszkodzenie."),

 dict(id="VI-14", dzial="VI", zakres=["D"], podstawa="KP",
  pytanie="Gdzie w zakładzie powinny znajdować się apteczki pierwszej pomocy?",
  odp=["W miejscach ustalonych z lekarzem medycyny pracy, oznakowanych i z wyznaczonymi osobami do obsługi",
       "Wyłącznie u kierownika zakładu",
       "W dowolnym miejscu, byle jedna na zakład",
       "W pokoju służby BHP"],
  ok=0,
  wyj="Przy każdej apteczce wywiesza się instrukcję udzielania pierwszej pomocy i wykaz osób przeszkolonych. Sama apteczka bez wyznaczonych osób nie spełnia wymogu."),

 dict(id="VI-15", dzial="VI", zakres=["D","E"], podstawa="KP",
  pytanie="Jaki jest prawidłowy stosunek uciśnięć do oddechów ratowniczych u dorosłego?",
  odp=["30 uciśnięć na 2 oddechy", "15 na 2", "5 na 1", "10 na 1"],
  ok=0,
  wyj="Jeśli ratownik nie chce lub nie może prowadzić wentylacji, wykonuje same uciśnięcia bez przerw. Reanimację prowadzi się do przyjazdu służb albo powrotu oddechu."),

 dict(id="IX-07", dzial="IX", zakres=["D"], podstawa="BHP2019",
  pytanie="Dlaczego przy pracach na sieci trakcyjnej wymagane jest potwierdzenie wyłączenia od dyżurnego ruchu?",
  odp=["Bo tylko dyspozytor zna faktyczny układ zasilania odcinka i może zablokować ponowne załączenie",
       "Bo wymaga tego regulamin przewozu osób",
       "Bo dyżurny wydaje narzędzia",
       "Nie jest wymagane, wystarczy wyłącznik lokalny"],
  ok=0,
  wyj="Sieć trakcyjna jest zasilana odcinkowo z wielu podstacji. Wyłączenie jednego wyłącznika nie gwarantuje braku napięcia na całym odcinku roboczym."),

 dict(id="IX-08", dzial="IX", zakres=["D","E"], podstawa="BHP2019",
  pytanie="Jak sprawdzić brak napięcia w sieci trakcyjnej prądu stałego?",
  odp=["Wskaźnikiem przeznaczonym do napięcia stałego danego zakresu, sprawdzonym bezpośrednio przed i po próbie",
       "Wskaźnikiem do napięcia przemiennego 230 V",
       "Dotykając sieci wierzchem dłoni",
       "Obserwując, czy nie ma iskrzenia"],
  ok=0,
  wyj="Wskaźniki do prądu przemiennego działające na zasadzie pojemnościowej nie wykrywają napięcia stałego. To typowa i groźna pomyłka."),

 dict(id="I-42", dzial="I", zakres=["D"], podstawa="BHP2019",
  pytanie="Zespół zgłasza zakończenie pracy telefonicznie. Co musi zrobić dopuszczający przed likwidacją miejsca pracy?",
  odp=["Upewnić się, że wszyscy opuścili strefę i że usunięto narzędzia oraz uziemiacze",
       "Natychmiast załączyć zasilanie po zgłoszeniu telefonicznym",
       "Poczekać 15 minut i załączyć zasilanie",
       "Zlecić kontrolę służbie BHP"],
  ok=0,
  wyj="Pozostawiony uziemiacz przy załączeniu powoduje zwarcie z łukiem. Dlatego zwrot uziemiaczy potwierdza się w poleceniu pisemnie."),

 dict(id="I-43", dzial="I", zakres=["D"], podstawa="BHP2019",
  pytanie="Podczas pracy okazuje się, że potrzebna jest dodatkowa osoba w zespole. Jak postąpić?",
  odp=["Zmianę składu zespołu wprowadza poleceniodawca, a fakt odnotowuje się w poleceniu",
       "Kierujący zespołem dobiera dowolną osobę bez formalności",
       "Nowa osoba dołącza po ustnym pouczeniu",
       "Nie wolno zmieniać składu, pracę trzeba przerwać na stałe"],
  ok=0,
  wyj="Każdy nowy członek zespołu musi zostać dopuszczony i poinstruowany o zagrożeniach w tym konkretnym miejscu pracy."),

 dict(id="I-44", dzial="I", zakres=["D"], podstawa="BHP2019",
  pytanie="Czy kierujący zespołem może jednocześnie wykonywać prace fizyczne przy urządzeniu?",
  odp=["Tak, jeżeli zespół liczy do dwóch osób łącznie z nim i pozwala na to charakter pracy",
       "Nigdy, musi wyłącznie nadzorować",
       "Tak, zawsze, niezależnie od liczebności zespołu",
       "Tylko za pisemną zgodą inspektora pracy"],
  ok=0,
  wyj="W większym zespole nadzór wymaga pełnej uwagi. Przy pracach szczególnie niebezpiecznych kierujący nie wykonuje czynności roboczych w ogóle."),

 dict(id="II-28", dzial="II", zakres=["D","E"], podstawa="PN60364",
  pytanie="Jaka jest dopuszczalna wartość napięcia dotykowego w warunkach normalnych dla prądu przemiennego?",
  odp=["50 V", "230 V", "120 V", "12 V"],
  ok=0,
  wyj="W warunkach zwiększonego zagrożenia, na przykład w wykopach czy kotłach, granicę obniża się do 25 V. Dla prądu stałego odpowiednikiem jest 120 V."),

 dict(id="II-29", dzial="II", zakres=["D"], podstawa="PN60364",
  pytanie="Co to jest napięcie krokowe?",
  odp=["Różnica potencjałów między stopami stojącego człowieka na powierzchni ziemi przy przepływie prądu zwarciowego",
       "Napięcie na zaciskach przewodu ochronnego",
       "Spadek napięcia na długości obwodu",
       "Napięcie występujące przy każdym załączeniu odbiornika"],
  ok=0,
  wyj="Przy zerwanym przewodzie leżącym na ziemi obowiązuje wychodzenie ze strefy drobnymi krokami albo skokami złączonymi nogami."),

 dict(id="IV-21", dzial="IV", zakres=["D"], podstawa="PN60364",
  pytanie="Czego dowodzi pomiar impedancji pętli zwarcia w układzie TN?",
  odp=["Że prąd zwarciowy jest wystarczająco duży, aby zabezpieczenie wyłączyło obwód w wymaganym czasie",
       "Że rezystancja izolacji jest dostateczna",
       "Że przewód neutralny jest ciągły",
       "Że wyłącznik różnicowoprądowy działa"],
  ok=0,
  wyj="Warunek samoczynnego wyłączenia zapisuje się jako iloczyn impedancji pętli i prądu wyłączającego nieprzekraczający napięcia fazowego."),

 dict(id="X-19", dzial="X", zakres=["D"], podstawa="PE",
  pytanie="Kiedy urządzenie elektroenergetyczne można przekazać do eksploatacji?",
  odp=["Po zakończeniu prób i pomiarów pomontażowych z wynikiem pozytywnym oraz sporządzeniu dokumentacji odbiorowej",
       "Po zakończeniu montażu, pomiary można wykonać później",
       "Po ustnym potwierdzeniu wykonawcy",
       "Po pierwszym miesiącu pracy próbnej"],
  ok=0,
  wyj="Dokumentacja odbiorowa obejmuje protokoły pomiarów, dokumentację powykonawczą i instrukcję eksploatacji. Bez niej odbiór jest nieskuteczny."),
]
