# -*- coding: utf-8 -*-
"""Dzialy III, V-X — strefy Ex, agregaty, pomoc przedlekarska, elektrotermia,
fotowoltaika, trakcja, przepisy. Partia druga."""

P = [
 dict(id="III-07", dzial="III", zakres=["D","E"], podstawa="ATEX",
  pytanie="Co oznacza oznaczenie grupy II w urządzeniach przeciwwybuchowych?",
  odp=["Urządzenie przeznaczone do pracy poza górnictwem podziemnym",
       "Urządzenie wyłącznie do kopalń metanowych",
       "Drugi stopień szczelności obudowy",
       "Urządzenie na napięcie powyżej 1 kV"],
  ok=0,
  wyj="Grupa I to wyrobiska górnicze zagrożone metanem, grupa II cała reszta przemysłu. W grupie II wyróżnia się jeszcze kategorie 1G, 2G, 3G zależnie od strefy."),

 dict(id="III-08", dzial="III", zakres=["D"], podstawa="ATEX",
  pytanie="Urządzenie kategorii 2G wolno stosować w strefie:",
  odp=["1 i 2", "Wyłącznie 0", "Wyłącznie 2", "We wszystkich, łącznie z 0"],
  ok=0,
  wyj="Kategoria 1G jest wymagana w strefie 0 i może pracować we wszystkich, 2G w strefach 1 i 2, 3G tylko w strefie 2. Zasada: wyższa kategoria obejmuje strefy niższe."),

 dict(id="III-09", dzial="III", zakres=["D","E"], podstawa="ATEX",
  pytanie="Co oznacza grupa wybuchowości IIC?",
  odp=["Najbardziej wymagająca grupa, obejmująca wodór i acetylen",
       "Grupa dla metanu",
       "Najmniej wymagająca grupa gazów",
       "Oznaczenie stopnia ochrony obudowy"],
  ok=0,
  wyj="IIA to propan, IIB etylen, IIC wodór i acetylen. Urządzenie dla IIC nadaje się także do IIA i IIB, ale nie odwrotnie."),

 dict(id="V-05", dzial="V", zakres=["D"], podstawa="BHP2019",
  pytanie="Co grozi przy podłączeniu agregatu do instalacji budynku bez blokady wzajemnej?",
  odp=["Podanie napięcia do sieci zewnętrznej i porażenie ekipy pracującej na linii",
       "Wyłącznie uszkodzenie agregatu",
       "Przeciążenie odbiorników w budynku",
       "Nic, blokada jest zaleceniem, nie wymogiem"],
  ok=0,
  wyj="Zjawisko nazywa się zasilaniem zwrotnym. Blokada mechaniczna lub przełącznik z pozycją zerową są obowiązkowe."),

 dict(id="V-06", dzial="V", zakres=["D","E"], podstawa="BHP2019",
  pytanie="Jak należy postąpić z agregatem prądotwórczym w czasie tankowania?",
  odp=["Wyłączyć silnik i odczekać na jego ostygnięcie",
       "Tankować przy pracującym silniku, żeby nie stracić zasilania",
       "Tankować przy pracującym silniku, ale powoli",
       "Nie ma znaczenia, czy silnik pracuje"],
  ok=0,
  wyj="Paliwo rozlane na gorący silnik lub układ wydechowy może się zapalić. To zagrożenie pożarowe, nie elektryczne."),

 dict(id="VI-08", dzial="VI", zakres=["D","E"], podstawa="KP",
  pytanie="Jak uwolnić porażonego spod działania prądu, gdy nie da się wyłączyć zasilania?",
  odp=["Odciągnąć go przedmiotem izolacyjnym, stojąc na podłożu izolacyjnym",
       "Chwycić go za ubranie gołymi rękami",
       "Oblać wodą, żeby przerwać obwód",
       "Czekać na przyjazd pogotowia"],
  ok=0,
  wyj="Ratownik nie może stać się drugą ofiarą. Suchy drewniany drążek, gumowa mata i sucha odzież to minimum."),

 dict(id="VI-09", dzial="VI", zakres=["D","E"], podstawa="KP",
  pytanie="Jaka jest prawidłowa głębokość uciśnięć klatki piersiowej u osoby dorosłej?",
  odp=["5–6 cm", "2–3 cm", "8–10 cm", "Tak głęboko, jak się da"],
  ok=0,
  wyj="Przy częstości 100–120 uciśnięć na minutę. Zbyt płytkie uciśnięcia nie wytworzą przepływu krwi."),

 dict(id="VI-10", dzial="VI", zakres=["D"], podstawa="KP",
  pytanie="Kiedy można użyć automatycznego defibrylatora AED?",
  odp=["Gdy poszkodowany jest nieprzytomny i nie oddycha prawidłowo — urządzenie samo ocenia rytm",
       "Zawsze, gdy ktoś stracił przytomność",
       "Wyłącznie przez lekarza",
       "Nigdy przy porażeniu prądem"],
  ok=0,
  wyj="AED prowadzi ratownika głosem i wyładowuje tylko przy rytmie do defibrylacji. Przed użyciem trzeba osuszyć klatkę piersiową i odsunąć się od poszkodowanego."),

 dict(id="VI-11", dzial="VI", zakres=["D","E"], podstawa="KP",
  pytanie="Od czego zależy stopień obrażeń przy porażeniu prądem?",
  odp=["Od wartości prądu, czasu przepływu i drogi przez ciało",
       "Wyłącznie od napięcia",
       "Wyłącznie od mocy źródła",
       "Od rodzaju obuwia poszkodowanego"],
  ok=0,
  wyj="Najgroźniejsza jest droga przez klatkę piersiową, na przykład ręka–ręka albo ręka–nogi. Prąd rzędu 30 mA przepływający dłużej może wywołać migotanie komór."),

 dict(id="VII-04", dzial="VII", zakres=["D"], podstawa="BHP2019",
  pytanie="Jakie dodatkowe zagrożenie występuje przy piecach łukowych?",
  odp=["Promieniowanie nadfioletowe i olśnienie łukiem, grożące uszkodzeniem wzroku",
       "Wyłącznie hałas",
       "Zagrożenie wybuchem pyłu",
       "Brak zagrożeń poza porażeniem"],
  ok=0,
  wyj="Łuk elektryczny emituje silny nadfiolet. Konieczne są filtry ochronne o odpowiednim stopniu zaciemnienia, tak jak przy spawaniu."),

 dict(id="VII-05", dzial="VII", zakres=["D"], podstawa="BHP2019",
  pytanie="Dlaczego w pomieszczeniach elektrolizy konieczna jest wentylacja?",
  odp=["Bo na elektrodach wydziela się wodór, tworzący z powietrzem mieszaninę wybuchową",
       "Bo elektrolit szybko paruje",
       "Żeby chłodzić prostowniki",
       "Bo wymagają tego przepisy przeciwpożarowe dotyczące wszystkich pomieszczeń"],
  ok=0,
  wyj="Wodór jest lżejszy od powietrza i gromadzi się pod stropem. Dolna granica wybuchowości wynosi około 4% objętości."),

 dict(id="VIII-06", dzial="VIII", zakres=["D"], podstawa="PN60364",
  pytanie="Co powinien zawierać wyłącznik pożarowy prądu w budynku z instalacją fotowoltaiczną?",
  odp=["Możliwość odłączenia także strony DC, blisko modułów",
       "Wyłącznie odłączenie strony AC",
       "Wyłącznie sygnalizację świetlną",
       "Odłączenie licznika energii"],
  ok=0,
  wyj="Odłączenie samego AC zostawia napięcie na całej trasie kabli DC. Stosuje się optymalizatory albo wyłączniki przy modułach."),

 dict(id="VIII-07", dzial="VIII", zakres=["D","E"], podstawa="PN60364",
  pytanie="Jakiego typu wyłącznik różnicowoprądowy stosuje się w obwodzie falownika PV bez separacji galwanicznej?",
  odp=["Typu B, reagujący także na gładki prąd stały",
       "Typu AC", "Typu A", "Żadnego, RCD jest tam zbędny"],
  ok=0,
  wyj="Falownik beztransformatorowy może wprowadzić do obwodu AC składową stałą, która oślepia wyłączniki typu AC i A."),

 dict(id="VIII-08", dzial="VIII", zakres=["D"], podstawa="BHP2019",
  pytanie="Gdzie należy lokalizować magazyn energii z ogniwami litowo-jonowymi?",
  odp=["W pomieszczeniu wydzielonym pożarowo, z wentylacją i detekcją, poza drogami ewakuacji",
       "W dowolnym pomieszczeniu mieszkalnym",
       "Wyłącznie na zewnątrz budynku",
       "Na klatce schodowej, blisko wyjścia"],
  ok=0,
  wyj="Pożar ogniw litowych podtrzymuje się samoczynnie i wydziela toksyczne gazy. Umieszczenie przy drodze ewakuacji odcinałoby ją w razie pożaru."),

 dict(id="IX-04", dzial="IX", zakres=["D"], podstawa="BHP2019",
  pytanie="Czym są prądy błądzące przy trakcji prądu stałego?",
  odp=["Prądami powrotnymi płynącymi przez grunt, powodującymi korozję konstrukcji podziemnych",
       "Prądami zwarciowymi w podstacji",
       "Prądami indukowanymi w taborze",
       "Zjawiskiem występującym wyłącznie w trakcji prądu zmiennego"],
  ok=0,
  wyj="Część prądu powrotnego omija szyny i płynie gruntem. Powoduje to elektrochemiczną korozję rurociągów i zbrojenia."),

 dict(id="X-11", dzial="X", zakres=["D","E"], podstawa="KWAL2022",
  pytanie="Co się dzieje ze świadectwem kwalifikacyjnym po upływie pięciu lat?",
  odp=["Traci ważność i trzeba ponownie przystąpić do egzaminu",
       "Przedłuża się automatycznie",
       "Wystarczy szkolenie okresowe bez egzaminu",
       "Jest ważne bezterminowo, jeśli praca jest ciągła"],
  ok=0,
  wyj="Nie ma trybu przedłużenia bez egzaminu. Wniosek warto złożyć z wyprzedzeniem, żeby nie powstała przerwa w uprawnieniach."),

 dict(id="X-12", dzial="X", zakres=["D"], podstawa="KWAL2022",
  pytanie="Czy pracodawca może wystąpić z wnioskiem o egzamin dla swojego pracownika?",
  odp=["Tak, egzamin przeprowadza się na wniosek osoby zainteresowanej albo zatrudniającego ją pracodawcy",
       "Nie, wyłącznie osoba zainteresowana",
       "Tak, ale tylko dla uprawnień dozorowych",
       "Tak, ale wtedy świadectwo należy do pracodawcy"],
  ok=0,
  wyj="Świadectwo zawsze wydawane jest na osobę i pozostaje jej własnością niezależnie od tego, kto opłacił egzamin."),

 dict(id="X-13", dzial="X", zakres=["D"], podstawa="PE",
  pytanie="Ile osób wchodzi w skład komisji kwalifikacyjnej przeprowadzającej egzamin?",
  odp=["Trzy", "Jedna", "Dwie", "Pięć"],
  ok=0,
  wyj="Komisję powołuje Prezes URE. Egzamin ma formę ustną, a wynik ogłaszany jest bezpośrednio po nim."),

 dict(id="X-14", dzial="X", zakres=["D"], podstawa="PB",
  pytanie="Kto może przeprowadzać okresową kontrolę instalacji elektrycznej w obiekcie budowlanym?",
  odp=["Osoba posiadająca kwalifikacje wymagane przy wykonywaniu dozoru nad eksploatacją urządzeń elektroenergetycznych",
       "Właściciel obiektu osobiście",
       "Dowolny elektryk bez uprawnień",
       "Wyłącznie pracownik zakładu energetycznego"],
  ok=0,
  wyj="To jedno z konkretnych zastosowań uprawnień dozorowych. Wyniki kontroli wpisuje się do książki obiektu budowlanego."),

 dict(id="X-15", dzial="X", zakres=["D"], podstawa="KP",
  pytanie="Kto ponosi odpowiedzialność za stan bezpieczeństwa i higieny pracy w zakładzie?",
  odp=["Pracodawca, a w zakresie powierzonym także osoby kierujące pracownikami",
       "Wyłącznie służba BHP",
       "Wyłącznie pracownicy",
       "Społeczny inspektor pracy"],
  ok=0,
  wyj="Służba BHP pełni funkcję doradczą i kontrolną, ale odpowiedzialności z pracodawcy nie zdejmuje. Osoba dozoru odpowiada w zakresie swoich zadań."),
]
