# -*- coding: utf-8 -*-
"""Dzial I — Organizacja bezpiecznej pracy. Najwazniejszy dla DOZORU."""

P = [
 dict(id="I-01", dzial="I", zakres=["D","E"], podstawa="BHP2019",
  pytanie="Które z poniższych prac przy urządzeniach energetycznych wymagają wydania polecenia pisemnego?",
  odp=["Prace stwarzające możliwość wystąpienia szczególnego zagrożenia dla zdrowia i życia ludzkiego",
       "Wszystkie prace bez wyjątku, również oględziny",
       "Wyłącznie prace przy urządzeniach powyżej 1 kV",
       "Wyłącznie prace wykonywane przez podmioty zewnętrzne"],
  ok=0,
  wyj="Polecenie pisemne jest wymagane przy pracach stwarzających możliwość wystąpienia szczególnego zagrożenia dla zdrowia i życia. Pozostałe prace mogą być wykonywane na polecenie ustne lub bez polecenia, jeżeli wynikają z instrukcji eksploatacji."),

 dict(id="I-02", dzial="I", zakres=["D"], podstawa="BHP2019",
  pytanie="Kto jest uprawniony do wydania polecenia wykonania pracy przy urządzeniach energetycznych?",
  odp=["Poleceniodawca — osoba upoważniona przez prowadzącego eksploatację",
       "Każdy pracownik z uprawnieniami E",
       "Wyłącznie inspektor BHP",
       "Kierujący zespołem, po uzgodnieniu z zespołem"],
  ok=0,
  wyj="Polecenie wydaje poleceniodawca, czyli osoba wyznaczona i upoważniona przez prowadzącego eksploatację urządzeń energetycznych. To jedna z kluczowych ról dla osoby dozoru."),

 dict(id="I-03", dzial="I", zakres=["D","E"], podstawa="BHP2019",
  pytanie="Co obejmuje zakres pięciu podstawowych zasad bezpiecznej pracy przy urządzeniach elektroenergetycznych?",
  odp=["Wyłączenie, zabezpieczenie przed załączeniem, sprawdzenie braku napięcia, uziemienie i zwarcie, oznaczenie strefy pracy",
       "Wyłączenie, oznaczenie, ubranie rękawic, wezwanie nadzoru, wpisanie do dziennika",
       "Sprawdzenie napięcia, zgłoszenie dyspozytorowi, przeszkolenie zespołu, wyłączenie, uziemienie",
       "Zgłoszenie pracy, dopuszczenie, wykonanie pracy, odbiór, zakończenie"],
  ok=0,
  wyj="Pięć zasad w kolejności: wyłączyć, zabezpieczyć przed przypadkowym załączeniem, sprawdzić brak napięcia, uziemić i zewrzeć, oznaczyć i zabezpieczyć strefę pracy. Kolejność ma znaczenie — na egzaminie pytają o nią wprost."),

 dict(id="I-04", dzial="I", zakres=["D"], podstawa="BHP2019",
  pytanie="Jaka jest rola dopuszczającego przy organizacji pracy na polecenie?",
  odp=["Przygotowuje strefę pracy i dopuszcza zespół do jej wykonania",
       "Wydaje polecenie pisemne i wyznacza zakres prac",
       "Kieruje zespołem w trakcie wykonywania pracy",
       "Odbiera pracę i zamyka dokumentację"],
  ok=0,
  wyj="Dopuszczający przygotowuje strefę pracy zgodnie z poleceniem, sprawdza wykonanie czynności zabezpieczających i dopuszcza zespół do pracy. Nie wydaje polecenia — to rola poleceniodawcy."),

 dict(id="I-05", dzial="I", zakres=["D"], podstawa="BHP2019",
  pytanie="Kiedy wyznacza się koordynującego prace?",
  odp=["Gdy przy tym samym urządzeniu lub w tej samej strefie pracuje jednocześnie więcej niż jeden zespół",
       "Zawsze, gdy praca trwa dłużej niż jedną zmianę",
       "Wyłącznie przy pracach powyżej 1 kV",
       "Gdy w zespole jest więcej niż pięć osób"],
  ok=0,
  wyj="Koordynujący jest wyznaczany, gdy prace wykonuje jednocześnie kilka zespołów, także różnych pracodawców, i konieczne jest uzgodnienie ich działań w czasie i przestrzeni."),

 dict(id="I-06", dzial="I", zakres=["D","E"], podstawa="BHP2019",
  pytanie="Czym jest strefa pracy?",
  odp=["Wyznaczone i odpowiednio zabezpieczone miejsce, w którym wykonywana jest praca",
       "Cały obszar stacji elektroenergetycznej",
       "Pomieszczenie, w którym znajduje się rozdzielnica",
       "Obszar objęty ważnym poleceniem pisemnym, niezależnie od lokalizacji"],
  ok=0,
  wyj="Strefa pracy to wyznaczone miejsce wykonywania pracy, zabezpieczone i oznaczone tak, aby zespół nie zbliżył się do części pod napięciem poza strefą."),

 dict(id="I-07", dzial="I", zakres=["D"], podstawa="BHP2019",
  pytanie="Co musi zawierać polecenie pisemne na wykonanie pracy?",
  odp=["Zakres, miejsce i termin pracy, skład zespołu, wymagane środki zabezpieczające oraz osoby odpowiedzialne",
       "Wyłącznie zakres prac i nazwisko kierującego zespołem",
       "Wyłącznie datę i podpis poleceniodawcy",
       "Kosztorys pracy i listę materiałów"],
  ok=0,
  wyj="Polecenie określa m.in. zakres, miejsce i termin pracy, skład zespołu, osoby odpowiedzialne (kierujący, dopuszczający, nadzorujący, koordynujący) oraz warunki i środki zabezpieczające."),

 dict(id="I-08", dzial="I", zakres=["D","E"], podstawa="BHP2019",
  pytanie="Kiedy dopuszcza się wykonywanie prac przy urządzeniach energetycznych bez polecenia?",
  odp=["Przy czynnościach wynikających z instrukcji eksploatacji oraz przy ratowaniu zdrowia i życia lub zabezpieczaniu urządzeń przed zniszczeniem",
       "Zawsze, gdy pracownik posiada świadectwo kwalifikacyjne E",
       "Nigdy — każda praca wymaga polecenia",
       "Gdy praca trwa krócej niż godzinę"],
  ok=0,
  wyj="Bez polecenia wykonuje się czynności przewidziane instrukcją eksploatacji oraz działania ratownicze i zabezpieczające przed zniszczeniem urządzeń. Po takich działaniach należy je niezwłocznie zgłosić przełożonemu."),

 dict(id="I-09", dzial="I", zakres=["D"], podstawa="BHP2019",
  pytanie="Co powinna zawierać instrukcja eksploatacji urządzenia energetycznego?",
  odp=["Charakterystykę urządzenia, zasady obsługi, czynności przy uruchamianiu i zatrzymywaniu, zasady postępowania w razie awarii oraz wymagania BHP i ppoż.",
       "Wyłącznie dane znamionowe urządzenia",
       "Wyłącznie harmonogram przeglądów",
       "Schemat elektryczny i listę części zamiennych"],
  ok=0,
  wyj="Instrukcja eksploatacji to podstawowy dokument osoby dozoru. Obejmuje charakterystykę urządzenia, obsługę, uruchamianie i zatrzymywanie, postępowanie w razie awarii i pożaru oraz wymagania BHP."),

 dict(id="I-10", dzial="I", zakres=["D","E"], podstawa="BHP2019",
  pytanie="Jaka jest minimalna liczba osób wykonujących pracę na polecenie w warunkach szczególnego zagrożenia?",
  odp=["Co najmniej dwie osoby",
       "Jedna osoba z uprawnieniami D",
       "Trzy osoby, w tym nadzorujący",
       "Liczba zależy wyłącznie od decyzji kierującego zespołem"],
  ok=0,
  wyj="Prace stwarzające szczególne zagrożenie wykonuje się co najmniej w dwie osoby, aby możliwe było udzielenie natychmiastowej pomocy."),

 dict(id="I-11", dzial="I", zakres=["D"], podstawa="KP",
  pytanie="Jaki obowiązek ma osoba kierująca pracownikami w zakresie BHP?",
  odp=["Organizować pracę w sposób zapewniający bezpieczne i higieniczne warunki oraz egzekwować przestrzeganie przepisów BHP",
       "Wyłącznie prowadzić ewidencję czasu pracy",
       "Wyłącznie zgłaszać wypadki do inspekcji pracy",
       "Wyłącznie zapewnić odzież roboczą"],
  ok=0,
  wyj="Kodeks pracy nakłada na osoby kierujące pracownikami obowiązek organizowania pracy w sposób bezpieczny, dbania o sprawność środków ochrony i egzekwowania przestrzegania przepisów. To pytanie wraca na egzaminach dozorowych."),

 dict(id="I-12", dzial="I", zakres=["D","E"], podstawa="BHP2019",
  pytanie="Co należy zrobić po zakończeniu pracy wykonywanej na polecenie pisemne?",
  odp=["Wyprowadzić zespół ze strefy pracy, usunąć zabezpieczenia i zgłosić zakończenie pracy poleceniodawcy",
       "Wyłącznie odnotować pracę w dzienniku i opuścić obiekt",
       "Pozostawić uziemienia do następnej zmiany",
       "Zgłosić zakończenie dopiero po odbiorze technicznym"],
  ok=0,
  wyj="Zakończenie pracy obejmuje wyprowadzenie zespołu, usunięcie środków zabezpieczających i uziemień, a następnie zgłoszenie zakończenia poleceniodawcy — dopiero wtedy urządzenie może być załączone."),

 dict(id="I-13", dzial="I", zakres=["D"], podstawa="BHP2019",
  pytanie="Kim jest nadzorujący w organizacji pracy przy urządzeniach energetycznych?",
  odp=["Osobą wyznaczoną do sprawowania nadzoru nad zespołem, która nie wykonuje pracy fizycznej",
       "Osobą kierującą zespołem i jednocześnie wykonującą pracę",
       "Przedstawicielem służby BHP obecnym przy pracy",
       "Inspektorem nadzoru budowlanego"],
  ok=0,
  wyj="Nadzorujący wyłącznie nadzoruje zespół i nie może jednocześnie wykonywać pracy. Wyznacza się go, gdy warunki pracy tego wymagają."),

 dict(id="I-14", dzial="I", zakres=["D","E"], podstawa="BHP2019",
  pytanie="W jakiej kolejności sprawdza się brak napięcia w miejscu pracy?",
  odp=["Sprawdza się działanie wskaźnika napięcia, następnie brak napięcia na urządzeniu, a potem ponownie sprawność wskaźnika",
       "Wystarczy jednokrotne sprawdzenie na urządzeniu",
       "Sprawdza się wyłącznie stan łączników w rozdzielnicy",
       "Wystarczy potwierdzenie telefoniczne od dyspozytora"],
  ok=0,
  wyj="Wskaźnik napięcia sprawdza się przed użyciem i po użyciu, na źródle napięcia o znanej obecności. Bez tego brak wskazania może oznaczać uszkodzony przyrząd, a nie brak napięcia."),

 dict(id="I-15", dzial="I", zakres=["D"], podstawa="PE",
  pytanie="Kto odpowiada za utrzymanie urządzeń energetycznych we właściwym stanie technicznym?",
  odp=["Prowadzący eksploatację urządzeń energetycznych",
       "Wyłącznie producent urządzenia",
       "Wyłącznie operator systemu dystrybucyjnego",
       "Urząd Regulacji Energetyki"],
  ok=0,
  wyj="Obowiązek utrzymania urządzeń w należytym stanie technicznym spoczywa na prowadzącym eksploatację, a wykonują go osoby o odpowiednich kwalifikacjach pod nadzorem osób dozoru."),

 dict(id="I-16", dzial="I", zakres=["D","E"], podstawa="BHP1997",
  pytanie="Co oznacza obowiązek stosowania środków ochrony zbiorowej przed indywidualnymi?",
  odp=["Najpierw należy usunąć zagrożenie u źródła lub odgrodzić je dla wszystkich, a dopiero gdy to niemożliwe — stosować ochrony osobiste",
       "Środki zbiorowe stosuje się tylko w zakładach powyżej 50 pracowników",
       "Oba rodzaje środków są równorzędne i wybiera je pracownik",
       "Środki indywidualne są zawsze skuteczniejsze"],
  ok=0,
  wyj="Hierarchia środków ochronnych: eliminacja zagrożenia, ochrona zbiorowa, organizacja pracy, dopiero na końcu środki ochrony indywidualnej."),

 dict(id="I-17", dzial="I", zakres=["D"], podstawa="BHP2019",
  pytanie="Co powinno zawierać zgłoszenie gotowości urządzenia do pracy po zakończeniu remontu?",
  odp=["Potwierdzenie usunięcia zabezpieczeń i uziemień, wyprowadzenia zespołu oraz sprawdzenia stanu urządzenia",
       "Wyłącznie podpis kierownika remontu",
       "Wyłącznie protokół z pomiarów rezystancji izolacji",
       "Wyłącznie ustne zgłoszenie dyspozytorowi"],
  ok=0,
  wyj="Przed ponownym załączeniem należy potwierdzić, że strefa jest pusta, zabezpieczenia i uziemienia usunięte, a urządzenie sprawne. Dopiero wtedy dopuszczający zgłasza gotowość."),

 dict(id="I-18", dzial="I", zakres=["D","E"], podstawa="BHP2019",
  pytanie="Jak należy postąpić, gdy w trakcie pracy warunki uległy zmianie w sposób zagrażający bezpieczeństwu?",
  odp=["Przerwać pracę, wyprowadzić zespół ze strefy i powiadomić poleceniodawcę",
       "Kontynuować pracę i odnotować zmianę w dzienniku",
       "Zwiększyć liczbę osób w zespole i pracować dalej",
       "Poczekać na koniec zmiany i zgłosić to następnego dnia"],
  ok=0,
  wyj="Przy zmianie warunków zagrażającej bezpieczeństwu pracę należy bezzwłocznie przerwać i wyprowadzić zespół. Prawo i obowiązek przerwania pracy ma zarówno kierujący zespołem, jak i osoba dozoru."),
]
