# -*- coding: utf-8 -*-
"""Dzialy II i IV — ochrona przeciwporazeniowa oraz pomiary, partia druga."""

P = [
 dict(id="II-13", dzial="II", zakres=["D","E"], podstawa="PN60364",
  pytanie="Co oznacza układ sieci TN-C-S?",
  odp=["Przewód PEN jest rozdzielony na PE i N w pewnym punkcie instalacji i dalej już nie łączony",
       "PEN jest wspólny na całej długości instalacji",
       "Punkt neutralny źródła jest izolowany",
       "Każdy odbiornik ma własny uziom"],
  ok=0,
  wyj="Po rozdzieleniu PEN nie wolno go ponownie łączyć. Rozdzielenie jest warunkiem stosowania wyłączników różnicowoprądowych."),

 dict(id="II-14", dzial="II", zakres=["D","E"], podstawa="PN60364",
  pytanie="Czym charakteryzuje się układ IT?",
  odp=["Punkt neutralny źródła jest izolowany od ziemi lub uziemiony przez dużą impedancję",
       "Punkt neutralny jest uziemiony bezpośrednio",
       "Nie stosuje się w nim przewodów ochronnych",
       "Obudowy nie są uziemiane"],
  ok=0,
  wyj="Pierwsze zwarcie doziemne nie powoduje przerwy w zasilaniu, dlatego układ stosuje się tam, gdzie ciągłość jest krytyczna, np. na salach operacyjnych. Wymaga stałej kontroli stanu izolacji."),

 dict(id="II-15", dzial="II", zakres=["D","E"], podstawa="PN60364",
  pytanie="Jaki jest maksymalny czas wyłączenia w układzie TN dla obwodów rozdzielczych?",
  odp=["5 s", "0,4 s", "0,2 s", "1 s"],
  ok=0,
  wyj="Dla obwodów końcowych do 32 A przy 230 V obowiązuje 0,4 s. Obwody rozdzielcze mają dłuższy dopuszczalny czas, bo nie są bezpośrednio dotykane przez użytkownika."),

 dict(id="II-16", dzial="II", zakres=["D","E"], podstawa="PN60364",
  pytanie="Co to jest ochrona przez separację elektryczną?",
  odp=["Zasilanie odbiornika z transformatora separacyjnego, bez połączenia z ziemią",
       "Odizolowanie odbiornika od podłoża matą gumową",
       "Zastosowanie podwójnej izolacji",
       "Uziemienie obudowy odbiornika"],
  ok=0,
  wyj="Brak połączenia z ziemią sprawia, że dotknięcie jednego przewodu nie zamyka obwodu. Warunek: do jednego transformatora podłącza się tylko jeden odbiornik."),

 dict(id="II-17", dzial="II", zakres=["D","E"], podstawa="PN60364",
  pytanie="Czym różni się SELV od PELV?",
  odp=["SELV nie ma połączenia z ziemią, PELV jest uziemiony",
       "SELV dotyczy prądu stałego, PELV zmiennego",
       "SELV ma wyższe napięcie",
       "To dwa określenia tego samego układu"],
  ok=0,
  wyj="Oba to obwody bardzo niskiego napięcia zasilane ze źródła bezpiecznego. FELV to układ, który nie spełnia wszystkich wymagań i wymaga dodatkowej ochrony."),

 dict(id="II-18", dzial="II", zakres=["D","E"], podstawa="PN60364",
  pytanie="Który wyłącznik różnicowoprądowy zadziała także przy prądzie stałym pulsującym i gładkim?",
  odp=["Typu B", "Typu AC", "Typu A", "Każdy"],
  ok=0,
  wyj="Typ AC reaguje tylko na prąd przemienny, typ A dodatkowo na pulsujący stały, typ B także na gładki prąd stały. Ten ostatni jest wymagany m.in. przy falownikach fotowoltaicznych i ładowarkach samochodowych."),

 dict(id="II-19", dzial="II", zakres=["D"], podstawa="PN60364",
  pytanie="Dlaczego w obwodzie z wyłącznikiem różnicowoprądowym nie wolno łączyć przewodu N z PE za wyłącznikiem?",
  odp=["Bo część prądu roboczego ominie człon pomiarowy i wyłącznik będzie zbędnie wyzwalał lub nie zadziała",
       "Bo zwiększy to opór pętli zwarcia",
       "Bo spowoduje to przepalenie bezpiecznika",
       "Bo jest to dozwolone i nic się nie stanie"],
  ok=0,
  wyj="RCD mierzy sumę prądów w przewodach roboczych. Połączenie N z PE za wyłącznikiem tworzy drogę obejścia i psuje pomiar. To częsty błąd wykonawczy."),

 dict(id="II-20", dzial="II", zakres=["D","E"], podstawa="PN61140",
  pytanie="Urządzenie klasy ochronności III zasilane jest:",
  odp=["Napięciem bardzo niskim SELV lub PELV",
       "Przez przewód ochronny PE",
       "Z izolacją podwójną",
       "Bezpośrednio z sieci 230 V"],
  ok=0,
  wyj="Do urządzeń klasy III nie wolno podłączać przewodu ochronnego. Klasa 0, bez żadnej ochrony dodatkowej, jest w Polsce niedopuszczalna."),

 dict(id="II-21", dzial="II", zakres=["D","E"], podstawa="PN60529",
  pytanie="Co oznacza druga cyfra w kodzie IP?",
  odp=["Stopień ochrony przed wodą", "Stopień ochrony przed pyłem",
       "Odporność mechaniczną", "Klasę ochronności urządzenia"],
  ok=0,
  wyj="Pierwsza cyfra dotyczy ciał stałych i pyłu, druga wody. Odporność na uderzenia opisuje osobny kod IK."),

 dict(id="II-22", dzial="II", zakres=["D"], podstawa="PN60364",
  pytanie="Jaki stopień ochrony jest wymagany w strefie 1 łazienki, czyli nad wanną?",
  odp=["Co najmniej IPX4", "IP20", "IPX0", "IP68"],
  ok=0,
  wyj="Strefy w łazience mają rosnące wymagania w miarę zbliżania się do wanny. W strefie 0, czyli wewnątrz wanny, dopuszcza się wyłącznie SELV do 12 V."),

 dict(id="II-23", dzial="II", zakres=["D"], podstawa="PN62305",
  pytanie="Jakie są trzy typy ograniczników przepięć i gdzie się je stosuje?",
  odp=["Typ 1 na wejściu obiektu, typ 2 w rozdzielnicy, typ 3 przy odbiorniku",
       "Typ 1 przy odbiorniku, typ 3 na wejściu",
       "Wszystkie typy montuje się w jednym miejscu",
       "Typ zależy wyłącznie od mocy odbiornika"],
  ok=0,
  wyj="Ochrona jest stopniowana — kolejne stopnie obniżają napięcie resztkowe. Między stopniami trzeba zachować odpowiednią długość przewodu albo zastosować dławik."),

 dict(id="II-24", dzial="II", zakres=["D","E"], podstawa="PN60364",
  pytanie="Czemu służy dodatkowe połączenie wyrównawcze miejscowe w łazience?",
  odp=["Wyrównaniu potencjałów części przewodzących dostępnych i obcych w tym pomieszczeniu",
       "Zwiększeniu przekroju przewodu ochronnego",
       "Zastąpieniu wyłącznika różnicowoprądowego",
       "Obniżeniu rezystancji uziemienia budynku"],
  ok=0,
  wyj="Nawet przy awarii różnica potencjałów między wanną, rurami a obudową odbiornika pozostaje bezpieczna. To ochrona niezależna od zadziałania zabezpieczeń."),

 dict(id="IV-11", dzial="IV", zakres=["D","E"], podstawa="PN60364",
  pytanie="Jakim napięciem probierczym mierzy się rezystancję izolacji obwodów SELV i PELV?",
  odp=["250 V DC", "500 V DC", "1000 V DC", "50 V DC"],
  ok=0,
  wyj="Wymagana rezystancja wynosi wtedy co najmniej 0,5 MΩ. Wyższe napięcie mogłoby uszkodzić urządzenia w obwodzie bardzo niskiego napięcia."),

 dict(id="IV-12", dzial="IV", zakres=["D","E"], podstawa="PN60364",
  pytanie="Co należy zrobić z odbiornikami przed pomiarem rezystancji izolacji instalacji?",
  odp=["Odłączyć je, bo mogą zafałszować wynik lub ulec uszkodzeniu",
       "Pozostawić podłączone i włączone",
       "Pozostawić podłączone, ale wyłączone",
       "Nie ma to znaczenia dla pomiaru"],
  ok=0,
  wyj="Urządzenia elektroniczne i ograniczniki przepięć mogą zostać uszkodzone napięciem probierczym 500 V, a równocześnie zaniżą zmierzoną rezystancję."),

 dict(id="IV-13", dzial="IV", zakres=["D","E"], podstawa="PN60364",
  pytanie="Jaką metodą mierzy się rezystancję uziemienia?",
  odp=["Metodą techniczną z dwiema elektrodami pomocniczymi albo metodą cęgową",
       "Wyłącznie omomierzem między uziomem a przewodem PE",
       "Miernikiem rezystancji izolacji",
       "Miernikiem pętli zwarcia"],
  ok=0,
  wyj="Elektrody pomocnicze, prądowa i napięciowa, trzeba rozstawić w odpowiedniej odległości. Zbyt bliskie ustawienie zaniża wynik."),

 dict(id="IV-14", dzial="IV", zakres=["D"], podstawa="PN60364",
  pytanie="Jak często wykonuje się pomiary ochronne w pomieszczeniach o zwiększonym zagrożeniu porażeniem?",
  odp=["Częściej niż w zwykłych — okresy skraca się do jednego roku",
       "Co pięć lat, tak jak wszędzie",
       "Tylko przy odbiorze instalacji",
       "Raz na dziesięć lat"],
  ok=0,
  wyj="Wilgoć, przewodzące podłoże i wysoka temperatura przyspieszają degradację izolacji. Osoba dozoru ustala terminy w instrukcji eksploatacji."),

 dict(id="IV-15", dzial="IV", zakres=["D","E"], podstawa="PN60364",
  pytanie="Co oznacza zbyt wysoka zmierzona impedancja pętli zwarcia?",
  odp=["Prąd zwarciowy może być za mały, by zabezpieczenie zadziałało w wymaganym czasie",
       "Instalacja jest szczególnie bezpieczna",
       "Rezystancja izolacji jest zbyt niska",
       "Uziemienie jest zbyt dobre"],
  ok=0,
  wyj="Wtedy trzeba zwiększyć przekrój przewodu, skrócić obwód albo zastosować zabezpieczenie o mniejszym prądzie zadziałania lub wyłącznik różnicowoprądowy."),

 dict(id="IV-16", dzial="IV", zakres=["D"], podstawa="PN60364",
  pytanie="Kto podpisuje protokół z pomiarów ochronnych i za co odpowiada?",
  odp=["Wykonujący pomiary, a osoba dozoru sprawdza i zatwierdza wniosek o przydatności do eksploatacji",
       "Wyłącznie właściciel obiektu",
       "Inspektor nadzoru budowlanego",
       "Nikt, protokół nie wymaga podpisu"],
  ok=0,
  wyj="To pytanie typowo dozorowe. Sam wynik liczbowy bez oceny i podpisu nie zamyka sprawy."),
]
