# -*- coding: utf-8 -*-
"""Dzialy II-IV — ochrona przeciwporazeniowa, strefy Ex, pomiary."""

P = [
 # ---------------- II. OCHRONA PRZECIWPORAZENIOWA ----------------
 dict(id="II-01", dzial="II", zakres=["D","E"], podstawa="PN60364",
  pytanie="Co oznacza układ sieci TN-C?",
  odp=["Funkcje przewodu neutralnego i ochronnego pełni jeden wspólny przewód PEN",
       "Przewody N i PE są rozdzielone na całej długości instalacji",
       "Punkt neutralny źródła jest izolowany od ziemi",
       "Części przewodzące dostępne są uziemione niezależnie od źródła"],
  ok=0,
  wyj="W układzie TN-C funkcje N i PE łączy przewód PEN. W TN-S są rozdzielone, w TN-C-S rozdzielają się w pewnym punkcie instalacji."),

 dict(id="II-02", dzial="II", zakres=["D","E"], podstawa="PN60364",
  pytanie="Czym charakteryzuje się układ sieci TT?",
  odp=["Punkt neutralny źródła jest uziemiony, a części przewodzące dostępne mają własne, niezależne uziemienie",
       "Punkt neutralny jest izolowany, a obudowy uziemione",
       "Przewód PEN łączy funkcje N i PE",
       "Wszystkie części przewodzące są połączone z punktem neutralnym źródła"],
  ok=0,
  wyj="W TT uziemienie odbiorcy jest niezależne od uziemienia źródła. Dlatego podstawowym zabezpieczeniem są tam wyłączniki różnicowoprądowe."),

 dict(id="II-03", dzial="II", zakres=["D","E"], podstawa="PN61140",
  pytanie="Na czym polega ochrona przed dotykiem bezpośrednim (ochrona podstawowa)?",
  odp=["Na uniemożliwieniu dotknięcia części czynnych, m.in. przez izolowanie, obudowy i przegrody",
       "Na samoczynnym wyłączeniu zasilania po wystąpieniu zwarcia",
       "Na zastosowaniu połączeń wyrównawczych",
       "Na uziemieniu obudów urządzeń"],
  ok=0,
  wyj="Ochrona podstawowa zapobiega dotknięciu części czynnych. Ochrona dodatkowa działa dopiero wtedy, gdy podstawowa zawiedzie — wtedy następuje np. samoczynne wyłączenie zasilania."),

 dict(id="II-04", dzial="II", zakres=["D","E"], podstawa="PN61140",
  pytanie="Jakie urządzenie należy do klasy ochronności II?",
  odp=["Urządzenie z izolacją podwójną lub wzmocnioną, bez zacisku ochronnego",
       "Urządzenie z zaciskiem PE, wymagające podłączenia przewodu ochronnego",
       "Urządzenie zasilane napięciem bardzo niskim SELV",
       "Urządzenie bez żadnej izolacji roboczej"],
  ok=0,
  wyj="Klasa I ma zacisk ochronny, klasa II ma izolację podwójną lub wzmocnioną i oznaczana jest symbolem kwadratu w kwadracie, klasa III jest zasilana napięciem bardzo niskim."),

 dict(id="II-05", dzial="II", zakres=["D","E"], podstawa="PN60364",
  pytanie="Jaki jest maksymalny dopuszczalny czas samoczynnego wyłączenia zasilania w układzie TN dla obwodów gniazd wtyczkowych do 32 A przy napięciu 230 V?",
  odp=["0,4 s", "5 s", "1 s", "0,2 s"],
  ok=0,
  wyj="Dla obwodów końcowych do 32 A w układzie TN przy 230 V czas wyłączenia wynosi 0,4 s. Dla obwodów rozdzielczych dopuszcza się 5 s."),

 dict(id="II-06", dzial="II", zakres=["D","E"], podstawa="PN60364",
  pytanie="Jaki znamionowy prąd różnicowy ma wyłącznik RCD stosowany jako ochrona uzupełniająca przed porażeniem?",
  odp=["Nie większy niż 30 mA", "300 mA", "100 mA", "500 mA"],
  ok=0,
  wyj="Ochronę uzupełniającą zapewnia RCD o prądzie różnicowym nie większym niż 30 mA. Wyłączniki 100–500 mA służą głównie do ochrony przeciwpożarowej."),

 dict(id="II-07", dzial="II", zakres=["D","E"], podstawa="PN60529",
  pytanie="Co oznacza stopień ochrony IP54?",
  odp=["Ochrona przed pyłem w ograniczonym zakresie i przed bryzgami wody z każdego kierunku",
       "Pełna pyłoszczelność i ochrona przed zanurzeniem",
       "Ochrona przed ciałami stałymi powyżej 5 mm i kroplami wody padającymi pionowo",
       "Brak ochrony przed pyłem, ochrona przed strugą wody"],
  ok=0,
  wyj="Pierwsza cyfra to ochrona przed ciałami stałymi i pyłem (5 — ograniczona ochrona przed pyłem), druga przed wodą (4 — bryzgi z dowolnego kierunku)."),

 dict(id="II-08", dzial="II", zakres=["D","E"], podstawa="PN60364",
  pytanie="Jakie napięcie dotykowe dopuszczalne długotrwale przyjmuje się w warunkach normalnych dla prądu przemiennego?",
  odp=["50 V", "24 V", "120 V", "230 V"],
  ok=0,
  wyj="W warunkach normalnych 50 V AC, w warunkach zwiększonego zagrożenia (wilgoć, przewodzące otoczenie) wartość ta jest obniżana, np. do 25 V."),

 dict(id="II-09", dzial="II", zakres=["D"], podstawa="PN60364",
  pytanie="Czemu służą główne połączenia wyrównawcze w budynku?",
  odp=["Wyrównaniu potencjałów części przewodzących dostępnych i obcych, co ogranicza napięcie dotykowe",
       "Zwiększeniu prądu zwarciowego w instalacji",
       "Odprowadzeniu prądu roboczego do ziemi",
       "Zastąpieniu przewodu ochronnego PE"],
  ok=0,
  wyj="Połączenia wyrównawcze łączą PE z instalacjami metalowymi (wodną, gazową, CO, konstrukcją), wyrównując potencjały. Nie zastępują przewodu ochronnego."),

 dict(id="II-10", dzial="II", zakres=["D","E"], podstawa="PN60364",
  pytanie="W którym układzie sieci NIE wolno stosować wyłącznika różnicowoprądowego bezpośrednio za przewodem PEN?",
  odp=["W układzie TN-C, ponieważ PEN nie może być przerywany ani przechodzić przez RCD",
       "W układzie TT",
       "W układzie TN-S",
       "W układzie IT"],
  ok=0,
  wyj="Przewodu PEN nie wolno przerywać ani prowadzić przez człon pomiarowy RCD. Aby zastosować RCD, należy najpierw rozdzielić PEN na PE i N, przechodząc na układ TN-C-S."),

 dict(id="II-11", dzial="II", zakres=["D","E"], podstawa="PN60364",
  pytanie="Jakie barwy mają przewody ochronny PE oraz neutralny N?",
  odp=["PE — zielono-żółty, N — jasnoniebieski",
       "PE — jasnoniebieski, N — zielono-żółty",
       "PE — czarny, N — brązowy",
       "PE — czerwony, N — czarny"],
  ok=0,
  wyj="Zielono-żółty jest zarezerwowany wyłącznie dla przewodu ochronnego. Przewód PEN oznacza się zielono-żółto z niebieskimi końcówkami."),

 dict(id="II-12", dzial="II", zakres=["D"], podstawa="PN62305",
  pytanie="Czemu służy instalacja ograniczników przepięć (SPD) w rozdzielnicy?",
  odp=["Ograniczeniu przepięć atmosferycznych i łączeniowych do wartości bezpiecznej dla instalacji i odbiorników",
       "Zwiększeniu selektywności zabezpieczeń nadprądowych",
       "Zastąpieniu wyłącznika różnicowoprądowego",
       "Kompensacji mocy biernej"],
  ok=0,
  wyj="SPD odprowadzają energię przepięcia do układu uziemiającego. Dobiera się je w stopniach (typ 1, 2, 3) zależnie od miejsca instalacji."),

 # ---------------- III. STREFY ZAGROZONE WYBUCHEM ----------------
 dict(id="III-01", dzial="III", zakres=["D","E"], podstawa="ATEX",
  pytanie="Co oznacza strefa zagrożenia wybuchem nr 1 dla mieszanin gazowych?",
  odp=["Przestrzeń, w której atmosfera wybuchowa może wystąpić okresowo w trakcie normalnego działania",
       "Przestrzeń, w której atmosfera wybuchowa występuje stale lub długotrwale",
       "Przestrzeń, w której atmosfera wybuchowa występuje wyjątkowo i krótkotrwale",
       "Przestrzeń wolna od zagrożenia wybuchem"],
  ok=0,
  wyj="Strefa 0 — atmosfera wybuchowa stale lub długotrwale, strefa 1 — okresowo w normalnym działaniu, strefa 2 — rzadko i krótkotrwale. Dla pyłów odpowiednio strefy 20, 21 i 22."),

 dict(id="III-02", dzial="III", zakres=["D","E"], podstawa="ATEX",
  pytanie="Co oznacza rodzaj budowy przeciwwybuchowej oznaczony literą „d”?",
  odp=["Osłona ognioszczelna — wybuch wewnątrz obudowy nie przenosi się na zewnątrz",
       "Wykonanie iskrobezpieczne, ograniczające energię obwodu",
       "Obudowa hermetyczna wypełniona olejem",
       "Osłona gazowa z nadciśnieniem"],
  ok=0,
  wyj="„d” to osłona ognioszczelna, „i” — iskrobezpieczeństwo, „p” — osłona gazowa z nadciśnieniem, „o” — osłona olejowa, „e” — budowa wzmocniona."),

 dict(id="III-03", dzial="III", zakres=["D"], podstawa="ATEX",
  pytanie="Który dokument określa strefy zagrożenia wybuchem w zakładzie?",
  odp=["Dokument zabezpieczenia przed wybuchem",
       "Instrukcja eksploatacji urządzenia",
       "Protokół z pomiarów ochronnych",
       "Książka obiektu budowlanego"],
  ok=0,
  wyj="Dokument zabezpieczenia przed wybuchem sporządza pracodawca. Zawiera ocenę ryzyka wybuchu, wykaz stref i środki ochronne. Osoba dozoru powinna wiedzieć o jego istnieniu."),

 dict(id="III-04", dzial="III", zakres=["D","E"], podstawa="ATEX",
  pytanie="Co oznacza klasa temperaturowa T4 urządzenia przeciwwybuchowego?",
  odp=["Maksymalna temperatura powierzchni urządzenia nie przekracza 135°C",
       "Urządzenie pracuje w temperaturze otoczenia do 40°C",
       "Temperatura zapłonu mieszaniny wynosi 135°C",
       "Urządzenie wytrzymuje temperaturę 400°C"],
  ok=0,
  wyj="Klasy temperaturowe: T1 — 450°C, T2 — 300°C, T3 — 200°C, T4 — 135°C, T5 — 100°C, T6 — 85°C. Dotyczą maksymalnej temperatury powierzchni."),

 dict(id="III-05", dzial="III", zakres=["D"], podstawa="ATEX",
  pytanie="Czy w strefie zagrożonej wybuchem wolno wykonywać prace pożarowo niebezpieczne?",
  odp=["Tylko na podstawie odrębnego zezwolenia i po zabezpieczeniu strefy oraz pomiarach stężenia",
       "Tak, bez dodatkowych warunków, jeżeli wykonuje je osoba z uprawnieniami E",
       "Nie, w żadnym przypadku",
       "Tak, o ile praca trwa krócej niż 30 minut"],
  ok=0,
  wyj="Prace niebezpieczne pożarowo w strefach Ex wymagają pisemnego zezwolenia, pomiaru stężenia gazów lub pyłów, zabezpieczenia miejsca i nadzoru."),

 dict(id="III-06", dzial="III", zakres=["D","E"], podstawa="ATEX",
  pytanie="Jak należy postąpić z urządzeniem Ex, którego obudowa ognioszczelna została uszkodzona?",
  odp=["Wyłączyć je z eksploatacji do czasu naprawy przez uprawniony podmiot",
       "Naprawić doraźnie i kontynuować pracę",
       "Zwiększyć częstotliwość oględzin i użytkować dalej",
       "Zakleić uszkodzenie i odnotować w dzienniku"],
  ok=0,
  wyj="Uszkodzenie osłony ognioszczelnej znosi jej funkcję ochronną. Urządzenie należy wyłączyć z ruchu, a naprawy szczelin ognioszczelnych może wykonywać wyłącznie uprawniony podmiot."),

 # ---------------- IV. PRACE KONTROLNO-POMIAROWE ----------------
 dict(id="IV-01", dzial="IV", zakres=["D","E"], podstawa="PN60364",
  pytanie="Jakim napięciem wykonuje się pomiar rezystancji izolacji instalacji o napięciu znamionowym 230/400 V?",
  odp=["500 V DC", "230 V AC", "1000 V AC", "100 V DC"],
  ok=0,
  wyj="Dla instalacji do 500 V pomiar wykonuje się napięciem probierczym 500 V DC, a wymagana rezystancja izolacji wynosi co najmniej 1 MΩ."),

 dict(id="IV-02", dzial="IV", zakres=["D","E"], podstawa="PN60364",
  pytanie="Jaka jest minimalna wymagana rezystancja izolacji obwodu o napięciu znamionowym 230/400 V?",
  odp=["1 MΩ", "0,5 MΩ", "0,25 MΩ", "10 MΩ"],
  ok=0,
  wyj="Dla obwodów o napięciu do 500 V wymaga się co najmniej 1 MΩ. Dla obwodów SELV i PELV — 0,5 MΩ przy napięciu probierczym 250 V."),

 dict(id="IV-03", dzial="IV", zakres=["D","E"], podstawa="PN60364",
  pytanie="Co sprawdza pomiar impedancji pętli zwarcia?",
  odp=["Czy prąd zwarciowy jest dostatecznie duży, aby zabezpieczenie zadziałało w wymaganym czasie",
       "Czy rezystancja izolacji jest wystarczająca",
       "Czy uziom ma odpowiednio niską rezystancję",
       "Czy obciążenie faz jest symetryczne"],
  ok=0,
  wyj="Pomiar pętli zwarcia weryfikuje skuteczność samoczynnego wyłączenia zasilania. Zmierzoną impedancję porównuje się z wartością dopuszczalną dla danego zabezpieczenia."),

 dict(id="IV-04", dzial="IV", zakres=["D","E"], podstawa="BHP2019",
  pytanie="Kto może wykonywać pomiary ochronne w instalacjach elektrycznych?",
  odp=["Osoba posiadająca świadectwo kwalifikacyjne E z wpisem uprawniającym do wykonywania prac kontrolno-pomiarowych",
       "Każdy elektryk z wykształceniem zawodowym",
       "Wyłącznie osoba z uprawnieniami D",
       "Wyłącznie przedstawiciel operatora sieci"],
  ok=0,
  wyj="Świadectwo kwalifikacyjne musi zawierać wpis o pracach kontrolno-pomiarowych. Same uprawnienia E do obsługi i konserwacji nie wystarczają."),

 dict(id="IV-05", dzial="IV", zakres=["D"], podstawa="PB",
  pytanie="Jak często wykonuje się okresową kontrolę instalacji elektrycznej w obiekcie budowlanym?",
  odp=["Co najmniej raz na 5 lat",
       "Co najmniej raz w roku",
       "Co 10 lat",
       "Wyłącznie przy zmianie właściciela"],
  ok=0,
  wyj="Prawo budowlane wymaga kontroli instalacji elektrycznej i piorunochronnej co najmniej raz na 5 lat. Kontrole roczne dotyczą m.in. instalacji gazowych i przewodów kominowych."),

 dict(id="IV-06", dzial="IV", zakres=["D","E"], podstawa="PN60364",
  pytanie="Co powinien zawierać protokół z pomiarów ochronnych?",
  odp=["Dane obiektu, zastosowane przyrządy, metodę, wyniki, wartości dopuszczalne oraz wniosek o przydatności do eksploatacji",
       "Wyłącznie wyniki liczbowe",
       "Wyłącznie datę i podpis mierzącego",
       "Wyłącznie schemat instalacji"],
  ok=0,
  wyj="Protokół bez wniosku o przydatności instalacji do dalszej eksploatacji jest niekompletny. Osoba dozoru zatwierdza taki protokół."),

 dict(id="IV-07", dzial="IV", zakres=["D","E"], podstawa="PN60364",
  pytanie="Jak sprawdza się poprawność działania wyłącznika różnicowoprądowego?",
  odp=["Pomiarem prądu i czasu zadziałania miernikiem oraz przyciskiem TEST",
       "Wyłącznie przyciskiem TEST",
       "Pomiarem rezystancji izolacji obwodu",
       "Obserwacją pracy odbiorników"],
  ok=0,
  wyj="Przycisk TEST sprawdza tylko mechanizm wyzwalający. Pełne sprawdzenie wymaga pomiaru rzeczywistego prądu zadziałania i czasu wyłączenia."),

 dict(id="IV-08", dzial="IV", zakres=["D","E"], podstawa="PN60364",
  pytanie="Jaką wartość rezystancji uziemienia przyjmuje się zwykle jako dopuszczalną dla instalacji odgromowej budynku?",
  odp=["Nie większą niż 10 Ω", "Nie większą niż 100 Ω", "Nie większą niż 0,1 Ω", "Dowolną, bo norma tego nie określa"],
  ok=0,
  wyj="Dla uziomów instalacji odgromowej przyjmuje się zwykle wartość do 10 Ω. W układach z uziomem fundamentowym wartości bywają niższe."),

 dict(id="IV-09", dzial="IV", zakres=["D"], podstawa="BHP2019",
  pytanie="Czy pomiary w obwodach pod napięciem wymagają polecenia pisemnego?",
  odp=["Tak, jeżeli stwarzają możliwość wystąpienia szczególnego zagrożenia dla zdrowia i życia",
       "Nie, pomiary zawsze wykonuje się bez polecenia",
       "Tak, zawsze i bez wyjątku",
       "Tylko przy napięciu powyżej 1 kV"],
  ok=0,
  wyj="Decyduje ocena zagrożenia, a nie sam fakt wykonywania pomiaru. Prace pod napięciem zaliczane do szczególnie niebezpiecznych wykonuje się na polecenie pisemne i co najmniej w dwie osoby."),

 dict(id="IV-10", dzial="IV", zakres=["D","E"], podstawa="PN60364",
  pytanie="Co należy sprawdzić w pierwszej kolejności podczas odbioru nowej instalacji elektrycznej?",
  odp=["Wykonać oględziny przed przystąpieniem do pomiarów",
       "Zmierzyć rezystancję izolacji",
       "Zmierzyć impedancję pętli zwarcia",
       "Załączyć instalację pod napięcie i obserwować pracę"],
  ok=0,
  wyj="Sprawdzenie odbiorcze zaczyna się od oględzin instalacji bez napięcia — ocenia się dobór urządzeń, oznaczenia, połączenia i ochronę. Dopiero potem wykonuje się próby i pomiary."),
]
